/** 伯特利中學 整體評語代碼表 (Bethel High School Overall Comment Code Table) — 03/01/2024 */
const COMMENT_CODES = [
  { code: "A01", en: "A hard working and well behaved student who is worthy to be praised.", zh: "力學守規，殊堪嘉獎。" },
  { code: "A02", en: "A gifted student with brilliant academic performance and behavior.", zh: "天資頗好，品學俱優。" },
  { code: "A03", en: "A bright student who has excellent school results.", zh: "天資聰慧，成績優異。" },
  { code: "A04", en: "A clever student who has outstanding school performance.", zh: "天資聰穎，成績超群。" },
  { code: "A05", en: "An industrious student with brilliant school performance.", zh: "沉潛向學，成績斐然。" },
  { code: "A06", en: "A graceful and intelligent student who always strives for improvement.", zh: "秀外慧中，勵志圖進。" },
  { code: "A07", en: "A polite student who is diligent and hard working.", zh: "言行有禮，勤勉不怠。" },
  { code: "A08", en: "A clever student with excellent academic performance and behavior.", zh: "秉性聰明，品學兼優。" },
  { code: "A09", en: "Prudent character and superior school results.", zh: "品性沉實，成績優良。" },
  { code: "A10", en: "A student with outstanding character who focuses on his/her studies.", zh: "品性優良，學業專注。" },
  { code: "A11", en: "Diligent character and brilliant school results.", zh: "品端勤學，成績斐然。" },
  { code: "A12", en: "A student with good study and behavior habits and a flexible personality.", zh: "品學均優，性格靈活。" },
  { code: "A13", en: "A student with excellent leadership skills who has outstanding academic performance and behavior.", zh: "品學兼優，有領袖之才。" },
  { code: "A14", en: "Outstanding academic performance and behavior; the best student in the class.", zh: "品學兼優，為全班之冠。" },
  { code: "A15", en: "Excellent academic performance and behavior; the best student in the class.", zh: "品學兼優，班之翹楚。" },
  { code: "A16", en: "Good character with brilliant school results.", zh: "品學兼優，樂於服務。" },
  { code: "A17", en: "A student with excellent academic performance and behavior.", zh: "品學兼優。" },
  { code: "A18", en: "Good performance on study and behavior; a diligent student who is fond of learning.", zh: "品學優良，勤敏好學。" },
  { code: "A19", en: "A clever and studious student who has outstanding school performance.", zh: "敏而好學，成績優良。" },
  { code: "A20", en: "A gentle and polite student with brilliant school results.", zh: "溫文有禮，成績超群。" },
  { code: "A21", en: "Amiable and prudent character; satisfactory school results.", zh: "溫婉沉實，學業甚佳。" },
  { code: "A22", en: "A quiet and polite student with satisfactory school results.", zh: "嫻靜有禮，品學兼優。" },
  { code: "A23", en: "A hard-working student who is gentle and pleasant.", zh: "潛修力學，德性嫻淑。" },
  { code: "A24", en: "Graceful and dignified character; superior school results.", zh: "賦性端莊，學業優良。" },
  { code: "A25", en: "Excellent performance on study and behavior.", zh: "學行優良。" },
  { code: "B01", en: "A bright and intelligent student with prudent moral character.", zh: "天資聰穎，品格良好。" },
  { code: "B02", en: "Study diligently and behave morally; a student with great potential.", zh: "守規勤學，可造之材。" },
  { code: "B03", en: "Calm personality and devoted to learning.", zh: "沉靜向學，其志可嘉。" },
  { code: "B04", en: "A gentle and polite student who has excellent performance on behavior.", zh: "和順守規，溫文有禮。" },
  { code: "B05", en: "A student with satisfactory performance on behavior.", zh: "明心見性，品行甚佳。" },
  { code: "B06", en: "A student who makes a clear distinction between right and wrong and behaves accordingly.", zh: "明辨是非，應對有度。" },
  { code: "B07", en: "A polite and responsible student who has distinctive personality.", zh: "明禮節，重責任，品性優。" },
  { code: "B08", en: "Actively engaged in service; handling tasks with great efficiency.", zh: "服務熱誠，有辦事能力。" },
  { code: "B09", en: "A student who is obedient and willing to serve others.", zh: "服從教導，樂於服務。" },
  { code: "B10", en: "Humble and peaceful character; treating others with sincerity.", zh: "品性謙和，待人熱誠。" },
  { code: "B11", en: "A polite and well behaved student.", zh: "待人接物，彬彬有禮。" },
  { code: "B12", en: "A good and kind hearted student who is loyal and honest.", zh: "思想良善，忠誠可嘉。" },
  { code: "B13", en: "A student with a pure mind and outstanding character.", zh: "思想純正，品德亦優。" },
  { code: "B14", en: "An optimistic student with a high sense of responsibility.", zh: "為人樂觀，有責任心。" },
  { code: "B15", en: "A humble and polite student who is deeply admired and respected.", zh: "為人謙遜，得人愛戴。" },
  { code: "B16", en: "A loyal and sincere student who is worthy to be praised.", zh: "智慮忠純，誠樸可嘉。" },
  { code: "B17", en: "A friendly student with a mild and amiable characters.", zh: "善意迎人，態度溫文。" },
  { code: "B18", en: "A gentle and honest student who respects his teachers and loves his classmates.", zh: "敬師愛友，品性敦厚。" },
  { code: "B19", en: "Gentle and polite character; study diligently.", zh: "溫文有禮，讀書用功。" },
  { code: "B20", en: "A sincere and genuine person with good character.", zh: "誠摯可嘉，品格良好。" },
  { code: "B21", en: "A loyal and honest student with a graceful and dignified manner.", zh: "雍容爾雅，忠誠不阿。" },
  { code: "B22", en: "A poised and honest student with a graceful and dignified manner.", zh: "儀態淑嫻，大方正直。" },
  { code: "B23", en: "Graceful and dignified manners; modest and polite character.", zh: "儀態端莊，謙恭有禮。" },
  { code: "B24", en: "A student with outstanding leadership skills who is willing to serve the school.", zh: "熱心奉公，富領袖才能。" },
  { code: "B25", en: "A student with a loyal character and honest behavior.", zh: "賦性忠耿，誠實可嘉。" },
  { code: "B26", en: "A quiet, gentle and well behaved student.", zh: "賦性嫻靜，恪守校規。" },
  { code: "B27", en: "A student who is humble in words and behaves politely.", zh: "謙言慎行，謙恭有禮。" },
  { code: "B28", en: "An open-minded student who is gentle and friendly.", zh: "豁達大度，和藹可親。" },
  { code: "C01", en: "A bright and intelligent student who is top of the class.", zh: "天資聰慧，名列前茅。" },
  { code: "C02", en: "A bright and intelligent student with outstanding academic performance and behavior.", zh: "天資聰穎，學業優良。" },
  { code: "C03", en: "Study diligently with outstanding school results.", zh: "好學好問，成績優良。" },
  { code: "C04", en: "Satisfactory school results; able to keep up with the studies.", zh: "成績甚佳，保持紀錄。" },
  { code: "C05", en: "Outstanding academic performance.", zh: "成績超群。" },
  { code: "C06", en: "Brilliant school results; substantial improvement on study.", zh: "成績優異，竿頭猛進。" },
  { code: "C07", en: "Good school results; works hard to make better progress.", zh: "百尺竿頭，更求上進。" },
  { code: "C08", en: "A honest and hard working student with excellent academic performance.", zh: "沉實用功，成績優異。" },
  { code: "C09", en: "A clever and studious student with satisfactory school results.", zh: "敏而好學，成績甚佳。" },
  { code: "C10", en: "A student who constantly makes improvements; a bright and successful future is expected.", zh: "屢見進步，前程無可限量。" },
  { code: "C11", en: "A hard working student with a critical mind.", zh: "質疑問難，好學不倦。" },
  { code: "D01", en: "Diligent in study; prudent behavior; active in service.", zh: "力學守規，服務努力。" },
  { code: "D02", en: "A gifted student with excellent academic performance and behavior.", zh: "天資頗好，品學俱優。" },
  { code: "D03", en: "A hard working and prudent student who is willing to serve.", zh: "生性勤慎，勇於服務。" },
  { code: "D04", en: "A hard working, polite and well behaved student.", zh: "好學守規。" },
  { code: "D05", en: "A hard working student with decent behavior and a warm heart to serve.", zh: "好學守規，用心服務。" },
  { code: "D06", en: "An obedient student who perseveres in study.", zh: "安份守己，學有恆心。" },
  { code: "D07", en: "Obedient and hard-working.", zh: "守份安常，亦知奮發。" },
  { code: "D08", en: "A student who behaves morally and studies diligently.", zh: "守紀律，肯學習。" },
  { code: "D09", en: "A hard working student who strives for improvement.", zh: "有上進精神。" },
  { code: "D10", en: "A well behaved student who studies hard.", zh: "行檢依規，且能向學。" },
  { code: "D11", en: "A smart student who behaves well and studies attentively.", zh: "伶俐守規，用心於學。" },
  { code: "D12", en: "A prudent, quiet and well behaved student.", zh: "沉潛向學，知規知矩。" },
  { code: "D13", en: "Prudent and quiet personality; hard working on study.", zh: "沉靜好學。" },
  { code: "D14", en: "A quiet and obedient student who studies hard.", zh: "沉靜守規，刻苦用功。" },
  { code: "D15", en: "A calm student who is willing to learn.", zh: "沉靜受教。" },
  { code: "D16", en: "A calm student who is willing to learn and performs well at study.", zh: "沉靜受教，學業良好。" },
  { code: "D17", en: "A calm and sincere student who works hard.", zh: "沉靜勤懇。" },
  { code: "D18", en: "A quiet student who is studious.", zh: "沉靜寡言，用心向學。" },
  { code: "D19", en: "A graceful and intelligent student.", zh: "秀外慧中。" },
  { code: "D20", en: "A gentle and obedient student.", zh: "和順受教。" },
  { code: "D21", en: "A hard working student with a gentle and friendly personality.", zh: "性情和藹，勤學好問。" },
  { code: "D22", en: "A student who studies hard and behaves well.", zh: "知努力，亦守規。" },
  { code: "D23", en: "A student who works hard and obedient.", zh: "肯用功，亦守紀律。" },
  { code: "D24", en: "A hard working and disciplined student.", zh: "肯用功，守紀律。" },
  { code: "D25", en: "A student who is willing to study with self-respect.", zh: "肯用功，知自愛。" },
  { code: "D26", en: "Willing to help and support classmates.", zh: "肯扶助同學。" },
  { code: "D27", en: "Actively serving others; satisfactory school results.", zh: "勇於服務，成績頗佳。" },
  { code: "D28", en: "An active student who is energetic and ambitious.", zh: "勇於進取，活潑有為。" },
  { code: "D29", en: "Improved behavior and school results.", zh: "品已改善，學有進益。" },
  { code: "D30", en: "A gentle and polite student who is able to keep up with his studies.", zh: "品性和順，學業與時俱進。" },
  { code: "D31", en: "An honest and kind hearted student who is hard working on study.", zh: "品性忠厚，學業能勤。" },
  { code: "D32", en: "A kind and pure student who studies hard.", zh: "品性純良，亦頗向學。" },
  { code: "D33", en: "A kind and pure student with a humble attitude towards studies.", zh: "品性純良，虛心向學。" },
  { code: "D34", en: "A kind hearted student who has satisfactory school results.", zh: "品性純良，學業頗佳。" },
  { code: "D35", en: "A prudent student with satisfactory school results.", zh: "品性端淑，成績頗佳。" },
  { code: "D36", en: "Pure and loyal character; study diligently.", zh: "品質忠純，學亦勤奮。" },
  { code: "D37", en: "Substantial improvement on studies and behavior.", zh: "品學大有改善。" },
  { code: "D38", en: "Excellent performance on both study and behavior.", zh: "品學均佳。" },
  { code: "D39", en: "Steady improvement on study and behavior.", zh: "品學均循序漸進。" },
  { code: "D40", en: "Satisfactory academic performance and behavior; works harder to make further improvement.", zh: "品學尚佳，更盼努力。" },
  { code: "D41", en: "Satisfactory performance in both study and behavior.", zh: "品學尚佳。" },
  { code: "D42", en: "Good academic performance and behavior; works harder for further progress.", zh: "品學俱佳，更應努力向上。" },
  { code: "D43", en: "A friendly student who is hard working at study.", zh: "待人和氣，讀書用功。" },
  { code: "D44", en: "An energetic and hard-working student.", zh: "活潑上進。" },
  { code: "D45", en: "An energetic and studious student.", zh: "活潑好學。" },
  { code: "D46", en: "A lively student who is willing to study.", zh: "活潑有為，頗知用功。" },
  { code: "D47", en: "A very hard-working student who is focused on his studies.", zh: "苦學潛修。" },
  { code: "D48", en: "A kind and pure student who is willing to learn.", zh: "純良受教。" },
  { code: "D49", en: "A gentle and affable student who is willing to study.", zh: "能知向學，和藹可親。" },
  { code: "D50", en: "A well-organized student who studies hard.", zh: "做事有條理，學習知用功。" },
  { code: "D51", en: "A student who is well behaved and hard-working.", zh: "動靜有則，學業有恆。" },
  { code: "D52", en: "A prudent and persistent student who strives for the best in study.", zh: "堅毅沉實，力爭上游。" },
  { code: "D53", en: "A student who is able to focus on study and attain satisfactory school results.", zh: "專心向學，成績頗佳。" },
  { code: "D54", en: "A clever and studious student who is obedient.", zh: "敏而好學，守法服從。" },
  { code: "D55", en: "A steady and reliable student who makes progress at study.", zh: "循規蹈矩，學業漸進。" },
  { code: "D56", en: "A hard working and well behaved student.", zh: "敦品力學。" },
  { code: "D57", en: "A clever and studious student who studies hard.", zh: "勤敏向學。" },
  { code: "D58", en: "Hard working and focuses on study.", zh: "勤奮向學。" },
  { code: "D59", en: "A hard working and obedient student who is always ready to serve others.", zh: "勤慎守規，熱心服務。" },
  { code: "D60", en: "A promising student who studies hard.", zh: "勤奮向學，可造之材。" },
  { code: "D61", en: "A student who is diligent and obedient.", zh: "勤學守規。" },
  { code: "D62", en: "A very good student who is hard working and responsible.", zh: "勤學習，明責任，誠佳子弟。" },
  { code: "D63", en: "A hard working student who concentrates on study; a student with great potential.", zh: "勤謹向學，可造之材。" },
  { code: "D64", en: "A hard working and well behaved student who is willing to serve others.", zh: "勤謹守規，勇於服務。" },
  { code: "D65", en: "A well behaved student who studies hard.", zh: "馴謹守規，學亦勤勉。" },
  { code: "D66", en: "A responsible student who behaves morally and studies diligently.", zh: "盡責守規，向學亦勤。" },
  { code: "D67", en: "A well behaved student with satisfactory performance on behavior and studies.", zh: "頗肯自愛，品學不差。" },
  { code: "D68", en: "A quiet and studious student.", zh: "嫻靜好學。" },
  { code: "D69", en: "A gentle and quiet student who studies hard and behaves morally.", zh: "嫻靜好學，又知守規。" },
  { code: "D70", en: "A kind and pure student who has impressive improvement.", zh: "賦性純良，學有進境。" },
  { code: "D71", en: "Satisfactory academic performance and behavior.", zh: "學行尚佳。" },
  { code: "D72", en: "A hard-working student who is clean and tidy.", zh: "整潔用功。" },
  { code: "D73", en: "A student who is devoted to study and has brilliant characters.", zh: "勵志篤學，品性佳好。" },
  { code: "D74", en: "A humble and polite student who is hard-working.", zh: "謙恭有禮，勤謹好學。" },
  { code: "D75", en: "Discreet in word and deed; diligent in study.", zh: "謹言慎行，刻苦用功。" },
  { code: "D76", en: "A hard-working student who is gentle and polite.", zh: "讀書勤力，溫文有禮。" },
  { code: "D77", en: "A hard-working and responsible student.", zh: "讀書勤慎，做事負責。" },
  { code: "D78", en: "A conscientious student who works hard.", zh: "讀書勤奮，做事認真。" },
  { code: "E01", en: "An ingenious and honest student.", zh: "天真率直。" },
  { code: "E02", en: "A bright and intelligent student who is willing to serve others.", zh: "天資聰敏，富有服務精神。" },
  { code: "E03", en: "A student who is contented and behaves properly.", zh: "守份安常。" },
  { code: "E04", en: "A student who is willing to serve others.", zh: "有服務精神。" },
  { code: "E05", en: "A student with an orderly mind.", zh: "作事有條理。" },
  { code: "E06", en: "A responsible student.", zh: "作事負責。" },
  { code: "E07", en: "A quiet and obedient student.", zh: "沉靜守規。" },
  { code: "E08", en: "A quiet and friendly student.", zh: "沉靜和藹。" },
  { code: "E09", en: "A gentle and obedient student who is well behaved.", zh: "和順守規。" },
  { code: "E10", en: "A nice and friendly student.", zh: "和藹可親。" },
  { code: "E11", en: "A decent student with high potential.", zh: "性行均淑，可造之材。" },
  { code: "E12", en: "A kind and innocent student.", zh: "性行純良。" },
  { code: "E13", en: "A gentle and friendly student.", zh: "性情和善。" },
  { code: "E14", en: "A polite and responsible student.", zh: "明禮節，重責任。" },
  { code: "E15", en: "A competent student who is willing to serve others with a sincere heart.", zh: "服務熱誠，有辦事能力。" },
  { code: "E16", en: "An obedient student who is willing to learn from others; a student with great potential.", zh: "服從教導，可造之材。" },
  { code: "E17", en: "A student with good potential who is clever and talented.", zh: "秉性聰敏，可造之材。" },
  { code: "E18", en: "A student who is willing to serve others and take responsibilities.", zh: "勇於服務，敢於承擔。" },
  { code: "E19", en: "Big improvement on behavior.", zh: "品行有良好改進。" },
  { code: "E20", en: "A student with satisfactory academic performance and behavior.", zh: "品行尚佳。" },
  { code: "E21", en: "A gentle and honest student.", zh: "品性敦厚。" },
  { code: "E22", en: "A humble and gentle student.", zh: "品性謙和。" },
  { code: "E23", en: "A kind and gentle student with good school performance.", zh: "品學和善。" },
  { code: "E24", en: "A friendly student who gets along well with others.", zh: "待人和氣。" },
  { code: "E25", en: "A polite student with decent manners.", zh: "待人接物，彬彬有禮。" },
  { code: "E26", en: "A student with a sincere attitude towards others.", zh: "待人熱誠。" },
  { code: "E27", en: "A student with a pleasant personality.", zh: "品德尚佳。" },
  { code: "E28", en: "An outgoing and genuine student.", zh: "活潑率直。" },
  { code: "E29", en: "A responsible student who behaves morally.", zh: "負責守規。" },
  { code: "E30", en: "A gentle and polite student.", zh: "溫文有禮。" },
  { code: "E31", en: "A honest student who is worthy of praise.", zh: "誠實有嘉。" },
  { code: "E32", en: "An honest and sincere student with a decent personality.", zh: "誠摯可取，品格亦佳。" },
  { code: "E33", en: "A gentle and kind student who complies with the school rules.", zh: "馴善守規。" },
  { code: "E34", en: "A student who shows respect and concern to teachers.", zh: "對師長恭謹。" },
  { code: "E35", en: "Mild and gentle character.", zh: "態度溫文。" },
  { code: "E36", en: "A gifted and well behaved student.", zh: "頗有天聰，品格亦佳。" },
  { code: "E37", en: "A student who is quiet, gentle and affable.", zh: "嫻靜少言，態度和藹。" },
  { code: "E38", en: "A quiet and gentle student who is willing to serve others.", zh: "嫻靜守規，努力服務。" },
  { code: "E39", en: "A quiet and gentle student.", zh: "嫻靜有禮。" },
  { code: "E40", en: "A quiet and gentle student who strictly follow school rules.", zh: "賦性嫻靜，恪守校規。" },
  { code: "E41", en: "A humble and polite student.", zh: "謙恭有禮。" },
  { code: "E42", en: "A modest student who is polite and prudent.", zh: "謙恭有禮，謹守校規。" },
  { code: "E43", en: "A well behaved and helpful student with excellent performance on service.", zh: "謹守紀律，服務優良。" },
  { code: "E44", en: "A well behaved student who is careful on what he says and does.", zh: "謹言慎行。" },
  { code: "F01", en: "A gifted and talented student who studies hard.", zh: "天資敏慧，學不後人。" },
  { code: "F02", en: "A gifted and hard-working student.", zh: "天資頗佳，力學不倦。" },
  { code: "F03", en: "Improvements seen in the performance on different subjects.", zh: "各科成績均見進步。" },
  { code: "F04", en: "Improved results in different subjects; needs to work harder to make further progress.", zh: "各科成績進步，仍須向上。" },
  { code: "F05", en: "A student who studies hard.", zh: "向學尚勤。" },
  { code: "F06", en: "A student who can learn independently.", zh: "有自動學習精神。" },
  { code: "F07", en: "Substantial improvements in school results.", zh: "有顯著進步，應知自勵。" },
  { code: "F08", en: "A student who is willing to study hard.", zh: "尚肯用功。" },
  { code: "F09", en: "A intelligent and industrious who can learn independently.", zh: "性聰穎，又肯孜孜向學。" },
  { code: "F10", en: "A bright and intelligent student with a strong ability on understanding.", zh: "秉性聰穎，理解力強。" },
  { code: "F11", en: "A bright and intelligent student with a strong ability in learning.", zh: "秉性聰穎，學與時進。" },
  { code: "F12", en: "A student who is making progress gradually.", zh: "按步漸進。" },
  { code: "F13", en: "A hard working student who is eager to do well in study.", zh: "苦心孤詣，恥居人後。" },
  { code: "F14", en: "A student who has a better performance in English but needs to work harder on other subjects.", zh: "英文較佳，餘須努力。" },
  { code: "F15", en: "A very hard-working student who preserves in study.", zh: "埋頭苦幹，學有恆心。" },
  { code: "F16", en: "A modest student.", zh: "虛心向學。" },
  { code: "F17", en: "A very hard-working student.", zh: "勤奮力學。" },
  { code: "F18", en: "A very hard-working student with brilliant school results.", zh: "勤奮學業，成績璀璨。" },
  { code: "F19", en: "A student who is willing to work hard.", zh: "學尚勤勉。" },
  { code: "F20", en: "Improvement is seen in studies.", zh: "學業已見進步。" },
  { code: "F21", en: "A clever and studious student.", zh: "聰慧好學。" },
  { code: "F22", en: "A hard-working student.", zh: "讀書勤奮。" },
  { code: "G01", en: "A student who studies hard and makes small improvement in school results.", zh: "已知勤學，成績稍進。" },
  { code: "G02", en: "A student who works harder and makes small improvement in school results.", zh: "中庸之質，應知努力。" },
  { code: "G03", en: "A student who can make improvement if he works harder.", zh: "再加努力，進步可期。" },
  { code: "G04", en: "A smart student who has made a big improvement in study.", zh: "性頗機敏，學業頗進步。" },
  { code: "G05", en: "Average academic performance and behavior; should work harder.", zh: "品學平平，未見努力。" },
  { code: "G06", en: "A student who has average academic performance and behavior; needs to work harder.", zh: "品學平平，宜知努力。" },
  { code: "G07", en: "Improvements on behaviour and study; works hard to make better progress.", zh: "品學略有改善，仍須努力。" },
  { code: "G08", en: "Little progress in studies and behavior.", zh: "品學稍有進步。" },
  { code: "G09", en: "A prudent student with satisfactory school results.", zh: "思想頗純正，學業是中乘。" },
  { code: "G10", en: "Energetic and active, with stable academic results and conduct.", zh: "活潑好動，學行平穩。" },
  { code: "G11", en: "Quite hardworking and showing improvement.", zh: "漸知努力，進步可期。" },
  { code: "G12", en: "Quite intelligent but not hardworking or careful enough.", zh: "頗有聰明，但勤慎不足。" },
  { code: "G13", en: "Average in academic performance but needs to push yourself forward.", zh: "頗知自勵，學業平平。" },
  { code: "G14", en: "Learning is like rowing upstream, not to advance is to drop back.", zh: "學如逆水行舟，不進則退，宜勉之。" },
  { code: "G15", en: "Average performance in academic results and conduct.", zh: "學行平平。" },
  { code: "G16", en: "Little improvement in academic results and conduct.", zh: "學行未見進步。" },
  { code: "G17", en: "A little improvement in academic results and conduct.", zh: "學行略見進步。" },
  { code: "G18", en: "Quite concentrated on studies. Keep up and improvement is not far off.", zh: "學習頗專心，若能有恆，進步可期。" },
  { code: "G19", en: "Always bear in your mind: Perseverance is essential for studies.", zh: "學貴有恆，宜自勉之。" },
  { code: "H01", en: "Always energetic but seldom focused on studies.", zh: "好動有餘，努力不足。" },
  { code: "H02", en: "High intelligence but low aspiration.", zh: "有可造之資，無振奮之志。" },
  { code: "H03", en: "Silent and reserved and not able to push yourself forward.", zh: "沉默寡言，惜未能自勵。" },
  { code: "H04", en: "Acceptable compliance.", zh: "尚能守規。" },
  { code: "H05", en: "Quite silent.", zh: "性頗緘默。" },
  { code: "H06", en: "Improved conduct but the practice to defend himself/herself remains.", zh: "品行稍見改進，但強辯飾非之習未除。" },
  { code: "H07", en: "Improved conduct but still too energetic.", zh: "品行雖有改進，仍嫌好動。" },
  { code: "H08", en: "Able to stick to school regulations.", zh: "頗能遵守校規。" },
  { code: "H09", en: "Average conduct and should work hard for improvement.", zh: "操守平平，宜努力求進。" },
  { code: "I01", en: "Improved, keep it up!", zh: "已有進步，仍需努力。" },
  { code: "I02", en: "Intelligent but not willing to work hard.", zh: "天資頗佳，惜未肯力學。" },
  { code: "I03", en: "Progress is expected if you work harder.", zh: "如能用功，進步可期。" },
  { code: "I04", en: "Average academic performance and should work hard for improvement.", zh: "成績平平，應力求上進。" },
  { code: "I05", en: "Acceptable academic performance and you still need to work harder.", zh: "成績尚可，仍須努力不懈。" },
  { code: "I06", en: "Works hard but your performance is unstable.", zh: "沉著向學，尚有未穩。" },
  { code: "I07", en: "Quiet but not hardworking.", zh: "沉靜，惜未發奮求學。" },
  { code: "I08", en: "Work hard but you still need to improve.", zh: "沉靜向學，惜有未逮。" },
  { code: "I09", en: "Working quite hard.", zh: "尚知用功。" },
  { code: "I10", en: "Quite focused on studies.", zh: "尚知向學。" },
  { code: "I11", en: "Willing to work hard but not effective enough.", zh: "尚肯用功，惟欠速率。" },
  { code: "I12", en: "Needs to work hard.", zh: "尚須力爭上游。" },
  { code: "I13", en: "More efforts should be put on studies.", zh: "尚須努力向學。" },
  { code: "I14", en: "Willing to work hard and performance is satisfactory.", zh: "近知好學，亦稱人意。" },
  { code: "I15", en: "A little improvement but still needs to work hard.", zh: "略見進步，仍須努力。" },
  { code: "I16", en: "A little improvement and should work harder to catch up with peers.", zh: "略見進步，應急起直追。" },
  { code: "I17", en: "Not talented but quite hardworking.", zh: "資質平平，讀書頗努力。" },
  { code: "I18", en: "Quite hardworking but a few subjects not up to standard.", zh: "頗知向學，但數科未及水準。" },
  { code: "I19", en: "Quite hardworking.", zh: "頗知努力。" },
  { code: "I20", en: "Should pay more attention to studies.", zh: "學業仍須努力。" },
  { code: "I21", en: "Average in studies and should work very hard.", zh: "學業平平，亟宜努力。" },
  { code: "I22", en: "Ambitious and hardworking on studies but performance is not stable.", zh: "篤志力學，惜有未穩。" },
  { code: "I23", en: "Poor discipline and average academic results.", zh: "濡弱不振，學業平平。" },
  { code: "I24", en: "A little improvement but still needs to work hard.", zh: "雖有微進，仍須努力。" },
  { code: "J01", en: "Not attentive in classes and always talkative.", zh: "上課欠專心，且好談話。" },
  { code: "J02", en: "Not attentive in classes and unable to be disciplined.", zh: "上課欠專心，亦未能守紀律。" },
  { code: "J03", en: "Not attentive in classes and too lazy to study.", zh: "上課欠專心，學習亦懶散。" },
  { code: "J04", en: "Not attentive in classes and results not good.", zh: "上課未能專心，成績未如理想。" },
  { code: "J05", en: "Fail to comply with classroom regulations.", zh: "不遵教導，上課常不守規。" },
  { code: "J06", en: "Lazy and does not stick to regulations.", zh: "仍近疏懶，未盡守規。" },
  { code: "J07", en: "If the student does not exert himself/ herself in youth, he/ she will regret it in his/ her old age.", zh: "少壯不努力，老大徒傷悲，宜勉之。" },
  { code: "J08", en: "Not attentive and hardworking; Too energetic.", zh: "心散好動，未知勤學。" },
  { code: "J09", en: "Not attentive or serious on studies.", zh: "心猿意馬，學業草率。" },
  { code: "J10", en: "Not hardworking and disciplined.", zh: "欠努力，亦未能守紀律。" },
  { code: "J11", en: "Not hardworking; should learn to be less talkative.", zh: "未知用功，宜戒多言。" },
  { code: "J12", en: "Willful; not hardworking.", zh: "任性敷衍，未見勤勉。" },
  { code: "J13", en: "Willful and lazy.", zh: "任性懶散。" },
  { code: "J14", en: "Too energetic and talkative; not paying attention in class.", zh: "多言好玩，學不專心。" },
  { code: "J15", en: "Too energetic and talkative; not willing to work hard.", zh: "多言好動，不肯用功。" },
  { code: "J16", en: "Always fightful; not attentive to studies.", zh: "好勇鬥狠，不務於學。" },
  { code: "J17", en: "Too energetic and talkative; never hands in homework on time.", zh: "好動多言，常不依時交家課。" },
  { code: "J18", en: "Too energetic and talkative; not attentive to studies.", zh: "好動多言，學未專心。" },
  { code: "J19", en: "Always playful; not willing to work hard.", zh: "好嬉戲，未肯用功。" },
  { code: "J20", en: "Always talk; not willing to learn.", zh: "好談話，無心向學。" },
  { code: "J21", en: "Always talkative; doesn't do homework.", zh: "好談話，懶做家課。" },
  { code: "J22", en: "Not hardworking; always talking.", zh: "尚欠用功，且好談話。" },
  { code: "J23", en: "Too active to focus on studies.", zh: "性好動，影響學業。" },
  { code: "J24", en: "Too lazy to work hard on studies.", zh: "性疏懶，無心向學。" },
  { code: "J25", en: "Too playful to focus on studies.", zh: "玩心太重，影響學業。" },
  { code: "J26", en: "Average academic results and conduct; should have improvement.", zh: "品學平庸，宜知改進。" },
  { code: "J27", en: "Average academic results and conduct.", zh: "品學平庸。" },
  { code: "J28", en: "Should have improvement on studies and conduct.", zh: "品學均應改善。" },
  { code: "J29", en: "Too lazy to study but energetic; should have improvement.", zh: "疏懶好動，應加改善。" },
  { code: "J30", en: "Not showing efforts on studies; Always offends school regulations.", zh: "無心向學，時犯校規。" },
  { code: "J31", en: "Relatively poor academic performance; not serious on studies; should have improvement.", zh: "程度未逮，作業草率，宜加改善。" },
  { code: "J32", en: "Too childish; should take more initiative.", zh: "稚氣未除，缺少進取心。" },
  { code: "J33", en: "Not friendly to classmates; Not attentive in class.", zh: "對同學不友愛，學未專心。" },
  { code: "J34", en: "Unstable to concentrate; not smart enough.", zh: "精神欠集中，智力尚未足。" },
  { code: "J35", en: "Not serious and responsible; not focusing on studies.", zh: "敷衍塞責，無心向學。" },
  { code: "J36", en: "Not attentive in class; Always offends school regulations.", zh: "學不專心，時犯校規。" },
  { code: "J37", en: "Not attentive in class.", zh: "學不專心。" },
  { code: "J38", en: "Not hardworking; should have improvement on attitude.", zh: "學未用功，切宜改善。" },
  { code: "J39", en: "Not attentive in class; Always be impolite.", zh: "學未專心，語欠檢點。" },
  { code: "J40", en: "Fair in studies and conduct.", zh: "學行平庸。" },
  { code: "J41", en: "No improvement on studies and conduct.", zh: "學行未見改善。" },
  { code: "J42", en: "No progress on studies and conduct.", zh: "學行未見進步。" },
  { code: "J43", en: "Lag behind in studies and conduct.", zh: "學行均略退步。" },
  { code: "J44", en: "Not hardworking.", zh: "學習欠用功。" },
  { code: "J45", en: "Not attentive to studies and always talkative.", zh: "學習未能專心，且好談話。" },
  { code: "J46", en: "Lazy and not attentive.", zh: "懶散不專。" },
  { code: "K01", en: "Always talking and not attentive in class.", zh: "上課時好談話，不專心聽講。" },
  { code: "K02", en: "Always inattentive in class.", zh: "上課常不留心。" },
  { code: "K03", en: "Not sticking to class regulations and bullying classmates.", zh: "不守堂規，且欺同學。" },
  { code: "K04", en: "Not able to change bad habits.", zh: "不良習慣，未能克服。" },
  { code: "K05", en: "Being gifted but not self-disciplined.", zh: "天資頗好，惜欠自治能力。" },
  { code: "K06", en: "Not responsible.", zh: "欠責任心。" },
  { code: "K07", en: "Not sticking to class regulations.", zh: "未能恪守課室規則。" },
  { code: "K08", en: "Not sticking to school regulations; should be obedient.", zh: "未盡守規，宜知改進。" },
  { code: "K09", en: "Talkative and quick-tempered.", zh: "多言多事，性又躁急。" },
  { code: "K10", en: "Talkative and energetic.", zh: "多言好動，常生枝節。" },
  { code: "K11", en: "Talkative; not able to change bad habits.", zh: "好言好動，惡習未改。" },
  { code: "K12", en: "Talkative but timid.", zh: "好言畏事。" },
  { code: "K13", en: "Too defensive for himself/ herself; Not able to regret for what he/ she has done.", zh: "好爭辯，不思悔改。" },
  { code: "K14", en: "Talkative and energetic.", zh: "好動多言。" },
  { code: "K15", en: "Talkative and energetic; not sticking to regulations.", zh: "好動多言，不甚守規。" },
  { code: "K16", en: "Talkative and energetic; not willing to admit and improve.", zh: "好動多言，有過不改。" },
  { code: "K17", en: "Talkative and energetic; need to be disciplined.", zh: "好動多言，須加約束。" },
  { code: "K18", en: "Always nosy.", zh: "好理閒事。" },
  { code: "K19", en: "Always playful; not able to take care of himself/ herself.", zh: "好嬉戲缺乏自治能力。" },
  { code: "K20", en: "Always pretentious.", zh: "好矯揉造作。" },
  { code: "K21", en: "Unproper words and deeds.", zh: "言行不檢。" },
  { code: "K22", en: "Dishonest; should have improvement.", zh: "言行未見誠實，宜加改進。" },
  { code: "K23", en: "Not sticking to school regulations.", zh: "言動未盡守規。" },
  { code: "K24", en: "Talkative and energetic; can be rough.", zh: "好動多言，流於庸俗。" },
  { code: "K25", en: "Should greatly improve words and deeds.", zh: "言語舉動，亟宜改善。" },
  { code: "K26", en: "Always wayward and defensive.", zh: "性情剛愎好辯。" },
  { code: "K27", en: "Behaviour is getting worse.", zh: "品行日見退步。" },
  { code: "K28", en: "Always reckless.", zh: "品性鹵莽。" },
  { code: "K29", en: "Unwilling to change bad habits.", zh: "陋習頗多，未肯徹改。" },
  { code: "K30", en: "Always offends school regulations with no regret.", zh: "時犯校規，屢誡不改。" },
  { code: "K31", en: "Too talkative; improvement should be made.", zh: "時患多言，宜知改善。" },
  { code: "K32", en: "Little improvement on personality.", zh: "氣質仍未改善。" },
  { code: "K33", en: "Should learn to be self-disciplined.", zh: "缺乏自治能力。" },
  { code: "K34", en: "Too arrogant and always shifts his/ her responsibility.", zh: "缺乏責任心，態度驕慢。" },
  { code: "K35", en: "Impolite and rebellious.", zh: "缺乏禮貌，不守規則。" },
  { code: "K36", en: "Fail to comply with regulations.", zh: "常不守規。" },
  { code: "K37", en: "Always causing trouble; and bring unhygienic.", zh: "滋事畏難，不重清潔。" },
  { code: "K38", en: "Quite intelligent but too talkative.", zh: "資質頗佳，但欠安靜。" },
  { code: "K39", en: "Should pay more attention to school rules.", zh: "對課室規則應加注意。" },
  { code: "K40", en: "Always offends school regulations with no regret.", zh: "屢犯校規，未知悔改。" },
  { code: "K41", en: "Wayward; always refuse to listen to advice.", zh: "態度倔強，不易接受勸導。" },
  { code: "K42", en: "Getting more and more talkative.", zh: "漸好多言。" },
  { code: "K43", en: "Not serious in his/ her words.", zh: "說話不慎。" },
  { code: "K44", en: "Quite talkative.", zh: "頗好說話。" },
  { code: "K45", en: "Fair in conduct; should be more hardworking.", zh: "操守平庸宜努力向上。" },
  { code: "K46", en: "Too lazy and not responsible for himself/ herself.", zh: "懶惰成性，又乏責任心。" },
  { code: "L01", en: "Poor academic performance; should work harder.", zh: "不知用功，成績甚差。" },
  { code: "L02", en: "Not intelligent; Not good at studies.", zh: "天資略遜，成績欠佳。" },
  { code: "L03", en: "Not intelligent or hardworking enough.", zh: "天資稍拙，未知用功。" },
  { code: "L04", en: "Quite intelligent but not serious in doing homework.", zh: "天資頗好，惜作業草率。" },
  { code: "L05", en: "Not learning independently.", zh: "欠自動學習精神。" },
  { code: "L06", en: "Should improve his/ her attitude when doing homework.", zh: "功課草率，亟應改善。" },
  { code: "L07", en: "Not hardworking.", zh: "未肯用功。" },
  { code: "L08", en: "Should be more concentrated on studies.", zh: "未能專心向學。" },
  { code: "L09", en: "Should be more concentrated on learning to strive for better results.", zh: "未能專心學習，成績欠佳。" },
  { code: "L10", en: "A bit naive; not concentrating on studies.", zh: "年稍幼稚，未知向學。" },
  { code: "L11", en: "Fail in writing and Putonghua; should work harder.", zh: "作文國語俱不合格，宜努力用功。" },
  { code: "L12", en: "Sloppy homework; should work harder.", zh: "作業草率，未肯用功。" },
  { code: "L13", en: "Sloppy homework; no improvement can be seen.", zh: "作業潦草，未見改善。" },
  { code: "L14", en: "Sloppy homework with bad results.", zh: "作業潦草，成績欠佳。" },
  { code: "L15", en: "Sloppy homework; lazy.", zh: "作業潦草，讀書懶惰。" },
  { code: "L16", en: "Getting worse and worse.", zh: "每下愈況。" },
  { code: "L17", en: "Unable to concentrate on studies.", zh: "求學仍未專心。" },
  { code: "L18", en: "Should put more efforts on studies.", zh: "學業仍須多下苦功。" },
  { code: "L19", en: "Too lazy to do homework; poor academic results.", zh: "怠於功課，成績低劣。" },
  { code: "L20", en: "Not to advance is to drop back. Work hard!", zh: "為學不進則退，快努力。" },
  { code: "L21", en: "No serious in studies.", zh: "為學苟且。" },
  { code: "L22", en: "Weak in English; Work hard!", zh: "英文甚差，須加努力。" },
  { code: "L23", en: "Has difficulty in understanding.", zh: "理解力弱。" },
  { code: "L24", en: "Too lazy; should work harder.", zh: "略嫌懶惰，從此須加努力。" },
  { code: "L25", en: "Not concentrating on studies.", zh: "疏於力學。" },
  { code: "L26", en: "Not focusing on studies; should work harder.", zh: "疏懶學業，未知進取。" },
  { code: "L27", en: "Careless; not concentrating on studies.", zh: "粗心大意，學不專心。" },
  { code: "L28", en: "Sloppy homework; not concentrating on studies.", zh: "習作潦草，學不專心。" },
  { code: "L29", en: "Not intelligent.", zh: "智力較差。" },
  { code: "L30", en: "Should improve learning attitude.", zh: "無心向學，亟宜改善。" },
  { code: "L31", en: "Not up to standard and not hardworking.", zh: "程度既差，又不用功。" },
  { code: "L32", en: "Should concentrate on his/ her studies.", zh: "須沉潛力學。" },
  { code: "L33", en: "Quite intelligent but not concentrating on his/ her studies.", zh: "資質頗佳，惜未能專心向學。" },
  { code: "L34", en: "Should study harder.", zh: "對學業應加努力。" },
  { code: "L35", en: "Not intelligent; not concentrating on studies.", zh: "精神欠集中，智力尚未足。" },
  { code: "L36", en: "Not concentrating on studies; unsatisfactory.", zh: "精神散漫，成績欠佳。" },
  { code: "L37", en: "Not concentrating on studies; not working hard.", zh: "精神渙散，未知用功。" },
  { code: "L38", en: "Quite intelligent but not doing his/ her homework seriously.", zh: "頗有天聰，惜作業草率。" },
  { code: "L39", en: "Not concentrating on studies.", zh: "學未專心。" },
  { code: "L40", en: "Not concentrating on studies; should work hard.", zh: "學未專心，宜努力向上。" },
  { code: "L41", en: "Should study harder.", zh: "學習仍須努力。" },
  { code: "L42", en: "Not hardworking enough.", zh: "學習尚欠努力。" },
  { code: "L43", en: "Not concentrating on studies.", zh: "學習尚未專心。" },
  { code: "L44", en: "Average results; should work harder.", zh: "學業平庸，應力求上進。" },
  { code: "L45", en: "Average results; should know to work harder.", zh: "學業平庸，應知努力。" },
  { code: "L46", en: "Results are getting poorer; should work harder.", zh: "學業退步，應加努力。" },
  { code: "L47", en: "Too lazy; needs a great improvement.", zh: "懶惰苟且，亟宜改善。" },
  { code: "L48", en: "Lazy; lack of motivation for studying.", zh: "疏懶學業，乏進取心。" },
  { code: "L49", en: "Lack of perseverance in studies.", zh: "讀書欠恆心。" },
  { code: "L50", en: "Not studying hard enough.", zh: "讀書未見努力。" },
  { code: "L51", en: "Getting lazier and lazier.", zh: "讀書漸懶。" },
  { code: "M01", en: "Good results but too talkative in class.", zh: "成績尚佳，惟欠安靜。" },
  { code: "M02", en: "Quite hardworking and self-motivated but too playful.", zh: "自學頗勤，惜愛嬉戲。" },
  { code: "M03", en: "Hardworking but not sticking to school rules.", zh: "努力好學，惜未盡守規。" },
  { code: "M04", en: "Eager to learn.", zh: "求學心切，尚有可取。" },
  { code: "M05", en: "Quite impatient and bad-tempered but good at studies.", zh: "品性略嫌浮躁，幸學業良好。" },
  { code: "M06", en: "Hardworking but talkative.", zh: "能用功，惜好談話。" },
  { code: "M07", en: "Quite hardworking but not sticking to rules.", zh: "頗知力學，但嫌未能守規。" },
  { code: "M08", en: "Good at studies but always talkative.", zh: "學有心得，惜欠寧靜。" },
  { code: "M09", en: "Good at studies but talkative and too energetic.", zh: "學有心得，惜好言動。" },
  { code: "M10", en: "Average results; Need to change bad habits.", zh: "學業平常，陋習未改。" },
  { code: "N01", en: "Always quiet; If concentrate on studies, progress can be made.", zh: "沉默寡言，如能向學，進步可期。" },
  { code: "N02", en: "Comply with school regulations but needs to study hard.", zh: "尚能守規，仍應勤學。" },
  { code: "N03", en: "Nice character but not good at studies.", zh: "性頗融和，惟學業未達上進。" },
  { code: "N04", en: "Obedient but need to study hard.", zh: "知守規，但學未進益。" },
  { code: "N05", en: "Nice character but not motivated.", zh: "品性尚佳，學欠精神。" },
  { code: "N06", en: "Polite but weak in English; Needs to work hard.", zh: "待人和氣，惜英文甚差，宜用功。" },
  { code: "N07", en: "Quite energetic but not hardworking.", zh: "活潑有餘，惜學業荒疏。" },
  { code: "N08", en: "Obedient but not hardworking enough.", zh: "能謹守紀律，惟欠用功。" },
  { code: "N09", en: "Obedient but not concentrated on studies.", zh: "頗知守規，但學不專心。" },
  { code: "N10", en: "Obedient but more efforts has to be put on assignments.", zh: "頗能守規，功課尚應努力。" },
  { code: "N11", en: "Little improvement on studies but better behaviour.", zh: "學未進益，品有改善。" },
  { code: "N12", en: "Not motivated but obedient to teachers.", zh: "學習精神欠佳，尚幸能守紀律。" },
  { code: "N13", en: "Good behaviour but poor results.", zh: "操行良好，惜成績較差。" },
  { code: "N14", en: "Acceptable behaviour but average results.", zh: "操行尚佳，但學業平平。" },
  { code: "N15", en: "Some improvement in conduct but little improvement on studies.", zh: "操行較前改善，惟學業仍無進步。" },
  { code: "N16", en: "Some improvement in conduct but still needs to work harder.", zh: "舉止稍有改善，仍須努力學習。" },
  { code: "N17", en: "Obedient but should work harder.", zh: "雖知守規，未盡力學。" },
  { code: "N18", en: "Obedient but not hardworking.", zh: "雖能守規，未知用功。" },
  { code: "O01", en: "Intelligent but not serious about working.", zh: "天生聰明，惜做事敷衍。" },
  { code: "O02", en: "Not precise and thoughtful when working.", zh: "作事欠精細。" },
  { code: "O03", en: "Should learn to love himself/ herself and work seriously.", zh: "做事苟且，務宜努力自愛。" },
  { code: "O04", en: "Irresponsible.", zh: "作事敷衍塞責。" },
  { code: "O05", en: "Quiet; should work more effectively.", zh: "性頗嫻靜，惜辦事欠敏捷。" },
  { code: "O06", en: "Inefficient, should have improvement.", zh: "做事緩慢，應予改善。" },
  { code: "O07", en: "Intelligent but careless.", zh: "略具天聰，惜處事大意。" },
  { code: "P01", en: "Promoted to S.2.", zh: "升中二。" },
  { code: "P02", en: "Promoted to S.3.", zh: "升中三。" },
  { code: "P03", en: "Promoted to S.5.", zh: "升中五。" },
  { code: "P04", en: "Promoted to S.7.", zh: "升中七。" },
  { code: "P05", en: "Completed S.3.", zh: "完成中三。" },
  { code: "P06", en: "Completed S.5.", zh: "完成中五。" },
  { code: "P07", en: "Completed S.7.", zh: "完成中七。" },
  { code: "P08", en: "Repeat S.1.", zh: "重讀中一。" },
  { code: "P09", en: "Repeat S.2.", zh: "重讀中二。" },
  { code: "P10", en: "Repeat S.4.", zh: "重讀中四。" },
  { code: "P11", en: "NIL", zh: "補考後決定升／留級。" },
  { code: "P12", en: "Promoted to S.4.", zh: "升中四。" },
  { code: "P13", en: "Promoted to S.6.", zh: "升中六。" },
  { code: "P14", en: "Completed S.6.", zh: "完成中六。" },
  { code: "P15", en: "Repeat S.3.", zh: "重讀中三。" },
  { code: "P16", en: "Repeat S.5.", zh: "重讀中五。" },
  { code: "R01", en: "Playing truant for 1 day.", zh: "曠課一次。" },
  { code: "R02", en: "Playing truant for 2 days.", zh: "曠課兩次。" },
  { code: "R03", en: "Playing truant for 3 days.", zh: "曠課三次。" },
  { code: "R04", en: "Playing truant for 4 days.", zh: "曠課四次。" },
  { code: "R05", en: "Playing truant for 5 days.", zh: "曠課五次。" },
  { code: "R06", en: "Playing truant for 6 days.", zh: "曠課六次。" },
  { code: "R07", en: "Playing truant for 7 days.", zh: "曠課七次。" },
  { code: "R08", en: "Playing truant for 8 days.", zh: "曠課八次。" },
  { code: "R09", en: "Playing truant for 9 days.", zh: "曠課九次。" },
  { code: "R10", en: "Playing truant for 10 days.", zh: "曠課十次。" },
  { code: "R11", en: "Playing truant for 11 days.", zh: "曠課十一次。" },
  { code: "R12", en: "Playing truant for 12 days.", zh: "曠課十二次。" },
  { code: "R13", en: "Playing truant for 13 days.", zh: "曠課十三次。" },
  { code: "R14", en: "Playing truant for 14 days.", zh: "曠課十四次。" },
  { code: "R15", en: "Playing truant for 15 days.", zh: "曠課十五次。" },
  { code: "R16", en: "Playing truant for 16 days.", zh: "曠課十六次。" }
];

if (typeof module !== "undefined") module.exports = { COMMENT_CODES };
