window.PARTB_MARKING = {
  Jaylee: {
    theme: 1,
    themeTitle: "An Interpretation of a Chair",
    notes: "Strongest overall on Theme 1 — clear chair focus with confident perspective; push creativity and background colour further.",
    scores: { material: 11, visual: 11, creativity: 9, communication: 12 },
    feedback: [
      {
        key: "material",
        label: "Selection and Use of Material & Techniques",
        descriptor: "Medium handling is competent. The window reflection shows controlled technique, and light rendering on the red sofa creates a convincing sense of softness.",
        advice: "Push technique further with richer shading and more varied surface treatment on the ground and wall.",
      },
      {
        key: "visual",
        label: "Selection and Use of Visual Elements and Principles of Design",
        descriptor: "Good perspective with clear emphasis on the chair. The chair pattern works well.",
        advice: "Add elements in the foreground and further back to build stronger layered perspective, as commonly seen in Level 5+ exemplars. Give the ground and wall more colour, use complementary colours for shading, and consider a gradient background.",
      },
      {
        key: "creativity",
        label: "Creativity & Imagination",
        descriptor: "The theme is readable, but the interpretation is safe rather than especially creative or expressive.",
        advice: "Develop a more personal or surprising angle on the chair — what makes this interpretation uniquely yours?",
      },
      {
        key: "communication",
        label: "Communication of Theme",
        descriptor: "An Interpretation of a Chair comes through clearly. The visual presentation of the theme is straightforward and easy to follow.",
        advice: "You could strengthen the message further by making the chair's character or mood even more explicit.",
      },
    ],
  },
  Mandip: {
    theme: 1,
    themeTitle: "An Interpretation of a Chair",
    notes: "Background is the strongest element; the chair itself is too small and the piece reads as landscape rather than still life.",
    scores: { material: 7, visual: 8, creativity: 8, communication: 7 },
    feedback: [
      {
        key: "material",
        label: "Selection and Use of Material & Techniques",
        descriptor: "Colouring is acceptable across the surface.",
        advice: "Push colour more boldly and deliberately so the whole piece feels more finished.",
      },
      {
        key: "visual",
        label: "Selection and Use of Visual Elements and Principles of Design",
        descriptor: "The background is the strongest part of the composition. The chair, however, is too small to read clearly, so the work feels more like landscape painting than still life.",
        advice: "Scale the chair up so it dominates the composition and reads as the main subject.",
      },
      {
        key: "creativity",
        label: "Creativity & Imagination",
        descriptor: "There is some imaginative handling in the setting, but the chair does not dominate the idea strongly enough.",
        advice: "Centre the creative idea on the chair itself rather than the surrounding landscape.",
      },
      {
        key: "communication",
        label: "Communication of Theme",
        descriptor: "The theme is nominally the chair, but it is hard to see and therefore difficult to read as the main message.",
        advice: "Enlarge and foreground the chair so the theme communicates immediately to the viewer.",
      },
    ],
  },
  Aqsa: {
    theme: 2,
    themeTitle: "Take a Break",
    notes: "Some strong linework helps define a busy scene, but Take a Break is only partly communicated; perspective and colour still weaken the theme.",
    scores: { material: 11, visual: 10, creativity: 10, communication: 10 },
    feedback: [
      {
        key: "material",
        label: "Selection and Use of Material & Techniques",
        descriptor: "There is some good linework that helps separate and describe the many objects in the scene.",
        advice: "Build colour with more strength and conviction so it matches the quality of the linework.",
      },
      {
        key: "visual",
        label: "Selection and Use of Visual Elements and Principles of Design",
        descriptor: "The line work is a strength — it communicates a lot of objects clearly within the scene. Perspective is awkward in places and can read like a hand entering a box; colour remains weak overall.",
        advice: "Rework the perspective on the door and door sign, and strengthen colour across the piece.",
      },
      {
        key: "creativity",
        label: "Creativity & Imagination",
        descriptor: "There is an attempt at an unusual idea, but it does not yet come together as a clear or confident creative response.",
        advice: "Clarify the creative concept and how it connects to Take a Break.",
      },
      {
        key: "communication",
        label: "Communication of Theme",
        descriptor: "Take a Break is not fully communicated — there is no clear sense of someone actually pausing or resting.",
        advice: "Add a character or figure to show the theme more directly.",
      },
    ],
  },
  Biraz: {
    theme: 2,
    themeTitle: "Take a Break",
    notes: "The cat supports Take a Break; refine composition, lettering, marker use and still-life drawing.",
    scores: { material: 9, visual: 8, creativity: 9, communication: 9 },
    feedback: [
      {
        key: "material",
        label: "Selection and Use of Material & Techniques",
        descriptor: "Colouring is acceptable, though some marker strokes read as obvious rather than integrated.",
        advice: "Use complementary colours for shading and use markers to refine the edges of colour shapes instead of leaving heavy strokes.",
      },
      {
        key: "visual",
        label: "Selection and Use of Visual Elements and Principles of Design",
        descriptor: "The resting cat supports the composition, but scale and focus could be stronger; the apples are not drawn carefully enough.",
        advice: "Make the cat larger and more central, reduce the tree, and redraw the apples with more accuracy.",
      },
      {
        key: "creativity",
        label: "Creativity & Imagination",
        descriptor: "A straightforward but effective idea — the resting cat gives the work a gentle, personal quality.",
        advice: "Develop the scene around the cat a little further to enrich the imaginative reading.",
      },
      {
        key: "communication",
        label: "Communication of Theme",
        descriptor: "The cat suggests taking a break, which fits the theme well.",
        advice: "Be careful with the text 'BHS' — examiners may not understand it. Keep the thematic reading obvious.",
      },
    ],
  },
  Ibrahim: {
    theme: 2,
    themeTitle: "Take a Break",
    notes: "On theme with a clear sports-break idea; improve court perspective, figures and background.",
    scores: { material: 8, visual: 8, creativity: 9, communication: 9 },
    feedback: [
      {
        key: "material",
        label: "Selection and Use of Material & Techniques",
        descriptor: "Competent use of media, though the background colour feels flat.",
        advice: "Try a two-colour gradient background starting from the corners.",
      },
      {
        key: "visual",
        label: "Selection and Use of Visual Elements and Principles of Design",
        descriptor: "The sports-break scene is readable, but the badminton court lacks convincing perspective and only one player is shown.",
        advice: "Strengthen court perspective and consider two players to make the scene clearer.",
      },
      {
        key: "creativity",
        label: "Creativity & Imagination",
        descriptor: "A sensible interpretation of rest through sport — readable and appropriate for the theme.",
        advice: "Add detail that makes the pause moment feel more vivid or personal.",
      },
      {
        key: "communication",
        label: "Communication of Theme",
        descriptor: "Take a Break is communicated through a sporting pause.",
        advice: "Make the break moment clearer through figure action and setting.",
      },
    ],
  },
  Junaid: {
    theme: 2,
    themeTitle: "Take a Break",
    notes: "Weak theme and originality; strong dot background, but main forms — books and possible cat — need clearer drawing.",
    scores: { material: 6, visual: 7, creativity: 6, communication: 6 },
    feedback: [
      {
        key: "material",
        label: "Selection and Use of Material & Techniques",
        descriptor: "The complementary-colour dots in the background are an effective way to enrich the colour — the strongest colouring in the class. In the main subject area, however, the books are drawn with weak, uneven form and do not read clearly as solid objects. The shape at the bottom may have been meant as a cat, but it is not easily recognisable.",
        advice: "Draw the books with more stable, convincing shapes. If you intend a cat, define the outline more clearly and add telling details so the viewer can read it straight away.",
      },
      {
        key: "visual",
        label: "Selection and Use of Visual Elements and Principles of Design",
        descriptor: "There is visual interest in the background pattern, but the main subject area lacks focus and clear spatial structure.",
        advice: "Organise the composition around a clearer focal area so the viewer knows where to look first.",
      },
      {
        key: "creativity",
        label: "Creativity & Imagination",
        descriptor: "The piece imitates the scene of Will Barnet's Woman Reading (1965, plate 2b) rather than developing an original response.",
        advice: "Build an original figure and situation that belong to your own interpretation of the theme.",
      },
      {
        key: "communication",
        label: "Communication of Theme",
        descriptor: "Theme expression is very weak. There is no clear main character taking a break, and the lower form — possibly a cat — does not communicate rest or the theme clearly.",
        advice: "Include a readable figure resting or pausing so Take a Break is obvious at first glance.",
      },
    ],
  },
  Mhavish: {
    theme: 2,
    themeTitle: "Take a Break",
    notes: "Among the strongest on theme and personal meaning; linework handles a busy scene well, though colouring and figure drawing need the most development.",
    scores: { material: 10, visual: 11, creativity: 10, communication: 11 },
    feedback: [
      {
        key: "material",
        label: "Selection and Use of Material & Techniques",
        descriptor: "Colouring is weak relative to the strength of the idea, but the linework is effective in picking out and connecting the many objects across the scene.",
        advice: "Strengthen colour and overall technique so they match the ambition of the concept.",
      },
      {
        key: "visual",
        label: "Selection and Use of Visual Elements and Principles of Design",
        descriptor: "Good use of line helps communicate the different objects in a fairly full scene, and the composition supports the narrative.",
        advice: "Improve character anatomy and clarify the three figures in the top-right corner so their symbolic meaning reads more clearly.",
      },
      {
        key: "creativity",
        label: "Creativity & Imagination",
        descriptor: "A thoughtful personal interpretation — a break from stressful studying — with genuine imaginative potential.",
        advice: "Refine the visual storytelling so the symbolic figures and setting support the idea even more directly.",
      },
      {
        key: "communication",
        label: "Communication of Theme",
        descriptor: "On theme, with a clear and relatable reading of Take a Break in a student context.",
        advice: "Make the supporting symbols and figures clearer through stronger drawing and painting.",
      },
    ],
  },
  Nikhil: {
    theme: 2,
    themeTitle: "Take a Break",
    notes: "Strong colour and texture; theme communication and figure clarity are the main weaknesses.",
    scores: { material: 8, visual: 8, creativity: 8, communication: 6 },
    feedback: [
      {
        key: "material",
        label: "Selection and Use of Material & Techniques",
        descriptor: "Strong colouring and interesting stroke patterns create effective surface texture.",
        advice: "Extend the same controlled technique to figure drawing and form.",
      },
      {
        key: "visual",
        label: "Selection and Use of Visual Elements and Principles of Design",
        descriptor: "Visual elements are handled with energy, but figure drawing is weak and character focus is unclear.",
        advice: "Improve figure proportion and clarity so the viewer knows who is in the scene and what they are doing.",
      },
      {
        key: "creativity",
        label: "Creativity & Imagination",
        descriptor: "There is imaginative ambition in the concept, though the broken-mirror pun on 'break' is risky and not fully resolved.",
        advice: "Either resolve the pun more clearly or choose a concept that communicates Take a Break more directly.",
      },
      {
        key: "communication",
        label: "Communication of Theme",
        descriptor: "Not on theme. A visual pun on 'break' does not show Take a Break clearly, and headless figures make action and meaning hard to read.",
        advice: "Show resting or pausing through readable figures, clear action and a less ambiguous theme idea.",
      },
    ],
  },
  Soyal: {
    theme: 2,
    themeTitle: "Take a Break",
    notes: "Good colouring, but the compositional 'break' does not communicate the theme clearly enough.",
    scores: { material: 8, visual: 7, creativity: 8, communication: 6 },
    feedback: [
      {
        key: "material",
        label: "Selection and Use of Material & Techniques",
        descriptor: "Good colouring overall, with confident use of media in places.",
        advice: "Apply consistent colour control across the whole piece.",
      },
      {
        key: "visual",
        label: "Selection and Use of Visual Elements and Principles of Design",
        descriptor: "Splitting the composition in half is visually bold, but the design choices do not yet support a clear reading of the scene.",
        advice: "Align composition, figure placement and detail so the viewer can follow the scene more easily.",
      },
      {
        key: "creativity",
        label: "Creativity & Imagination",
        descriptor: "There is creative attempt in playing with the word 'break', though the idea needs stronger visual follow-through.",
        advice: "Develop the idea beyond the compositional split so the theme reads through content, not only format.",
      },
      {
        key: "communication",
        label: "Communication of Theme",
        descriptor: "Not on theme. The work should show resting or pausing, but character and action are unclear.",
        advice: "Clarify who the figure is, what they are doing, and make the Take a Break idea visible through action rather than wordplay alone.",
      },
    ],
  },
};
