window.PARTA_MARKING = {
  Aqsa: {
    scores: { description: 4, analysis: 4, interpretation: 3, judgement: 3 },
    notes: "Best in class, but not flawless: interpretation for 2b is mis-labelled as 2a; some description drifts into mood; judgement could compare both plates more formally.",
    highlights: [
      { text: "The media of both artworks is oil on canvas", category: "description", comment: "Literal Description — correct shared medium stated clearly." },
      { text: "woman sleeping on the bottom bunk, and a skeleton corpse on the top bunk", category: "description", comment: "Literal Description — accurate listing of key figures and bunkbed structure in 2a." },
      { text: "skeleton is surrounded with bombs", category: "description", comment: "Literal Description — notices bombs and bouquet, not just the skeleton." },
      { text: "She's reading a book while her cat rests undisturbed on her", category: "description", comment: "Literal Description — clear subject matter for 2b." },
      { text: "dull grey background and the bunkbed that's popping out with bright high-saturated colours yellow and brown", category: "analysis", comment: "Formal Analysis — strong contrast and saturation comparison." },
      { text: "skeleton is disproportionally large and it doesn't fit properly on the bed", category: "analysis", comment: "Formal Analysis — proportion and emphasis analysed, not just described." },
      { text: "red is a highly saturated colour that in contrast with the rest of the painting", category: "analysis", comment: "Formal Analysis — focal colour and contrast in 2b." },
      { text: "well balanced asymmetrically", category: "analysis", comment: "Formal Analysis — composition term used appropriately for 2b." },
      { text: "not everyone has happy endings", category: "interpretation", comment: "Interpretation — clear meaning read from Kahlo's juxtaposition of sleep and death." },
      { text: "person suffered a harsh death which included bombs and perhaps even war", category: "interpretation", comment: "Interpretation — develops symbolic reading of skeleton and bombs." },
      { text: "artist's message is to just relax to take a well needed break", category: "interpretation", comment: "Interpretation — intended reading of Barnet, though wrongly tagged as 2a in the script." },
      { text: "Artwork (2a) is definitely a success", category: "judgement", comment: "Value Judgement — evaluative claim, though criteria could be sharper." },
      { text: "I like artwork (2a) more because it's got more going on for it", category: "judgement", comment: "Value Judgement — stated preference with only general justification." },
    ],
  },
  Biraz: {
    scores: { description: 2, analysis: 1, interpretation: 2, judgement: 0 },
    notes: "Only plate 2b answered. No comparison with 2a, almost no formal analysis, no value judgement section.",
    highlights: [
      { text: "made by Will Barnet. It was made in 1965 and is Oil on canvas", category: "description", comment: "Literal Description — artist, date and medium correct for the one plate attempted." },
      { text: "woman reading her book while lying in bed and the white cat resting on top of the woman", category: "description", comment: "Literal Description — main subjects identified." },
      { text: "The way he painted the painting is simple but still very good", category: "analysis", comment: "Formal Analysis — only vague comment on style; no line, shape, composition or colour analysis." },
      { text: "The colour's Will Barnet use are soothing", category: "analysis", comment: "Formal Analysis — names colour effect, but as feeling rather than formal study." },
      { text: "resemble's the sky at night", category: "interpretation", comment: "Interpretation — symbolic reading of black background." },
      { text: "pillow and the mattress resemble's the cloud because it's soft", category: "interpretation", comment: "Interpretation — attempts metaphor for bedding forms." },
      { text: "the book she is reading resemble's to the woman's dream", category: "interpretation", comment: "Interpretation — links book to inner dream life." },
      { text: "That's what the artist wants to make you feel", category: "interpretation", comment: "Interpretation — states intended mood, but no judgement of success or comparison." },
    ],
  },
  Ibrahim: {
    scores: { description: 2, analysis: 1, interpretation: 1, judgement: 0 },
    notes: "Very short. Identifies both works but little formal analysis, thin interpretation, no real judgement.",
    highlights: [
      { text: "lady is sleeping on her bed. Her bed is cover by leafs and roots", category: "description", comment: "Literal Description — basic subject and surreal bed details in Dream." },
      { text: "person who is also sleeping the way she is", category: "description", comment: "Literal Description — notes parallel skeleton figure on upper bunk." },
      { text: "bed is flying is sky between the clouds", category: "description", comment: "Literal Description — observes floating bed setting." },
      { text: "created by Frida Kahlo in 1940 and the name of the artwork is called Dream", category: "description", comment: "Literal Description — artist, date and title for artwork 1." },
      { text: "lady laying on her bed and reading books and also telling story to her cat", category: "description", comment: "Literal Description — subject matter of Woman Reading." },
      { text: "created by will Barnet in 1965", category: "description", comment: "Literal Description — second artist and date." },
      { text: "Artwork 1 is 74 x 99 cm and the second one is 114 x 89 cm", category: "description", comment: "Literal Description — dimensions given; factual, not formal analysis." },
      { text: "just like who she is dreaming while", category: "interpretation", comment: "Interpretation — brief link between flying bed and dream, undeveloped." },
    ],
  },
  Jaylee: {
    scores: { description: 4, analysis: 3, interpretation: 3, judgement: 3 },
    notes: "Clear DIAC labels and strong exam technique. Analysis weakens when claiming Van Gogh did not use shapes/lines; judgement is good but repetitive.",
    highlights: [
      { text: "Artwork 1a is named \"Guitar on a Chair\". It was painted by Juan Gris in 1913, and is an oil on canvas artwork", category: "description", comment: "Literal Description — title, artist, date and medium for 1a." },
      { text: "He named his artwork \"Vincents' Chair with His Pipe\"", category: "description", comment: "Literal Description — title and artist for 1b." },
      { text: "Orange, green, brown, black and blue-grey", category: "description", comment: "Literal Description — palette listed for Gris." },
      { text: "He used fine, detailed lines on the chair and floor", category: "description", comment: "Literal Description — line quality observed in 1b." },
      { text: "There's contrast between the door and the chair", category: "analysis", comment: "Formal Analysis — contrast between forms in 1b." },
      { text: "movement and rythem in plate 1a looks like it moves and could play some music, however in plate 1b, it seems very still", category: "analysis", comment: "Formal Analysis — effective comparison of visual movement between plates." },
      { text: "1a is more darkish and seperated all over the place, however in plate 1b, it's more still and bright at the center", category: "analysis", comment: "Formal Analysis — compares tonal structure and focal area." },
      { text: "artist wants to show the movement of music", category: "interpretation", comment: "Interpretation — meaning proposed for Gris's cubist treatment." },
      { text: "Vincent van Gogh wanted to show his special chair, with his pipe on it", category: "interpretation", comment: "Interpretation — personal/symbolic reading of Van Gogh's subject." },
      { text: "I personally like plate 1b more, done by Vincent van Gogh because it connects to me more", category: "judgement", comment: "Value Judgement — clear preference stated." },
      { text: "gives me a harmonious feeling", category: "judgement", comment: "Value Judgement — personal evaluative response tied to formal qualities." },
      { text: "however Vincent, plate 1b didn't", category: "analysis", comment: "Formal Analysis — error: claims 1b lacks shapes/lines; weakens otherwise solid comparison." },
    ],
  },
  Junaid: {
    scores: { description: 3, analysis: 2, interpretation: 1, judgement: 2 },
    notes: "Lots of listing (colours, shapes, sizes) but little formal comparison or interpretation. Factual slips (86 years; 'he' for Kahlo).",
    highlights: [
      { text: "The name of this artwork is \"Dream\"", category: "description", comment: "Literal Description — identifies Kahlo work and title." },
      { text: "woman sleeping in a bed and she is dreaming", category: "description", comment: "Literal Description — subject matter of 2a." },
      { text: "skeleton who is also sleeping the same way as the woman", category: "description", comment: "Literal Description — parallel figures noted." },
      { text: "Oil on Canvas and the length and width 74 x 99 cm", category: "description", comment: "Literal Description — medium and dimensions for 2a." },
      { text: "woman laying down on the bed and she is reading a book while her cat is laying on her", category: "description", comment: "Literal Description — Barnet subject matter." },
      { text: "yellow color white color, black color, green color, orange color", category: "analysis", comment: "Formal Analysis — colours named only; no effect, contrast or composition discussed." },
      { text: "he use circle, rectangle, oval, cylinder and square", category: "analysis", comment: "Formal Analysis — shapes listed without analysing how they work in the image." },
      { text: "purple color for the eye is very beautiful", category: "analysis", comment: "Formal Analysis — notices focal detail on cat's eye; 'beautiful' is evaluative but observation is formal." },
      { text: "\"Dream\" the first artwork is more wider than \"Woman Reading\" the second artwork", category: "analysis", comment: "Formal Analysis — compares physical scale of works." },
      { text: "as if the artist \"Frida Kahlo\" is imagining a woman sleeping on a bed dreaming of something", category: "interpretation", comment: "Interpretation — only thin reading of artist intention; not developed for Barnet." },
      { text: "so it has 86 years when this artwork was made", category: "description", comment: "Literal Description — factual error undermines otherwise useful date information." },
      { text: "But \"Dream\" the first artwork has more shapes and color than \"Woman Reading\"", category: "judgement", comment: "Value Judgement — comparative claim, but not a full judgement of quality or success." },
    ],
  },
  Mandip: {
    scores: { description: 2, analysis: 1, interpretation: 2, judgement: 1 },
    notes: "Informal voice; mixes interpretation into description. Almost no formal analysis. No clear DIAC structure.",
    highlights: [
      { text: "Guitar on a chair made by Juan Gris 1913 oil on canvas 100 × 65 cm", category: "description", comment: "Literal Description — basic facts for 1a with dimensions." },
      { text: "Vincent's chair with his pipe. made by vincent van Gogh 1888 oil on canvas 93.0 × 73.5 cm", category: "description", comment: "Literal Description — basic facts for 1b." },
      { text: "they are both oil on canvas", category: "description", comment: "Literal Description — shared medium noted; factual, not formal analysis." },
      { text: "like Yellow, Brown, Blue, and white", category: "analysis", comment: "Formal Analysis — palette named only; no comparison of how colour is used." },
      { text: "guitar looks lonely alone in the chair no ones playing it", category: "interpretation", comment: "Interpretation — personal reading of mood; written inside description." },
      { text: "both the guitar and pipe looks alone not used", category: "interpretation", comment: "Interpretation — thematic loneliness comparison, not formal analysis." },
      { text: "Guitar on a chair was inspired from vincent's chair with His pipe", category: "interpretation", comment: "Interpretation — historical/link claim asserted without visual evidence." },
      { text: "the art both looks Sad and the guitar looks broken", category: "judgement", comment: "Value Judgement — emotional evaluation only; no structured success criteria." },
    ],
  },
  Mhavish: {
    scores: { description: 2, analysis: 2, interpretation: 1, judgement: 2 },
    notes: "Attempts all sections but confused (wrong plate refs, 'medieval', peasants). Interpretation often unrelated to the actual images.",
    highlights: [
      { text: "Dream the paint is on oil on canvas", category: "description", comment: "Literal Description — medium identified for 2a." },
      { text: "I can see a bed, skeleton and humun with different colours on", category: "description", comment: "Literal Description — main elements listed for 2a." },
      { text: "I can see book, cat, bed", category: "description", comment: "Literal Description — objects listed for 2b." },
      { text: "For the colours it's used a few colors red, white blue these all", category: "description", comment: "Literal Description — Barnet palette named; needs formal effect, not just listing." },
      { text: "background look so dirty", category: "analysis", comment: "Formal Analysis — texture/tonal comment on 2a background." },
      { text: "grey, white, yellow, some green curly lines", category: "analysis", comment: "Formal Analysis — colour and line identified in 2a." },
      { text: "used more geometric shapes for the humams, straight shaps while 2a used rounded corners", category: "analysis", comment: "Formal Analysis — shape comparison attempted between plates." },
      { text: "1a used much repetition and human gestures", category: "analysis", comment: "Formal Analysis — serious error: copies wrong plate/question reference (1a not in this paper)." },
      { text: "game-like activities", category: "interpretation", comment: "Interpretation — not grounded in Kahlo's Dream; drifts off the artwork." },
      { text: "watching a scuffle of peasants from a high perspective", category: "interpretation", comment: "Interpretation — invented content; weakens credibility of interpretation section." },
      { text: "I think 2a is better at relaying a theme and invoking conversation", category: "judgement", comment: "Value Judgement — preference stated, partly supported." },
      { text: "making it more entertaining than 2b", category: "judgement", comment: "Value Judgement — comparative evaluation, though informal." },
    ],
  },
  Nikhil: {
    scores: { description: 3, analysis: 2, interpretation: 2, judgement: 2 },
    notes: "Engaging voice but sections blur together. Limited formal comparison between plates; judgement mostly personal liking.",
    highlights: [
      { text: "Dream it's drawn by Frida Kahlo in 1940, Oil on canvas 74 × 99 cm", category: "description", comment: "Literal Description — title, artist, date, medium and size for 2a." },
      { text: "girl sleeping in the bed that is flying in the sky", category: "description", comment: "Literal Description — surreal setting observed." },
      { text: "skeleton that's tryna copy the girl sleeping she puts 2 pillows", category: "description", comment: "Literal Description — parallel figures and pillows noted." },
      { text: "many clouds of white and grey coloures", category: "analysis", comment: "Formal Analysis — background colour noted; needs more on composition/contrast." },
      { text: "blanket the girl is wearing is design of a tree roots connecting to her", category: "description", comment: "Literal Description — pattern on blanket described literally." },
      { text: "tree roots refers to life", category: "interpretation", comment: "Interpretation — symbolic reading of roots motif." },
      { text: "it's about dreams and fantasy i think it can be anything that you can think of", category: "interpretation", comment: "Interpretation — theme stated but general, not tied to specific visual choices." },
      { text: "Woman reading, drawn in oil on canvas, 114 × 89 cm", category: "description", comment: "Literal Description — facts for 2b." },
      { text: "cat eye's has lil bit annoyed cause she wants to play with the girl", category: "description", comment: "Literal Description — expression on cat observed." },
      { text: "so i like this painting a lot cause it's in an sky", category: "judgement", comment: "Value Judgement — preference for 2a; reason is thin." },
      { text: "I like this painting cause it shows emotions and bitterness in cat's eye", category: "judgement", comment: "Value Judgement — positive evaluation of 2b linked to mood, not full comparison." },
    ],
  },
  Soyal: {
    scores: { description: 2, analysis: 1, interpretation: 1, judgement: 1 },
    notes: "Both plates mentioned briefly. Weak grammar and structure; almost no formal analysis; judgement is one sentence.",
    highlights: [
      { text: "paint by Frida Kahlo one the best painter in 1940", category: "description", comment: "Literal Description — artist and date for 2a, though informally phrased." },
      { text: "there a bed and the person is sleeping on the bed and upper side its skeleton which is sleeping", category: "description", comment: "Literal Description — bunkbed figures described." },
      { text: "the paint size is 74 x 99cm", category: "description", comment: "Literal Description — size of 2a given." },
      { text: "woman reading the book she holding a book there a cat", category: "description", comment: "Literal Description — basic subject matter of 2b." },
      { text: "will Burnet on 1965 oil on canvas and the size the paint it 114 x 89cm", category: "description", comment: "Literal Description — artist, date, medium and size for 2b." },
      { text: "I like the colour red in the blanket", category: "analysis", comment: "Formal Analysis — notices focal colour only; no contrast, composition or line." },
      { text: "after u passed away u will go to the up in the peace", category: "interpretation", comment: "Interpretation — personal reading of death/peace in 2a, undeveloped." },
      { text: "it looked like she is already died", category: "interpretation", comment: "Interpretation — mood/meaning suggested, not supported with formal evidence." },
      { text: "plate 2a it very good well the meaning full too", category: "judgement", comment: "Value Judgement — preference for 2a without structured reasons or criteria." },
    ],
  },
};
