import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { spawnSync } from "child_process";

const dir = path.dirname(fileURLToPath(import.meta.url));
const parseSrc = fs.readFileSync(path.join(dir, "vocab-data.js"), "utf8");
const parseVocabRaw = new Function(`${parseSrc}; return parseVocabRaw;`)();
const text = fs.readFileSync(path.join(dir, "raw"), "utf8");
const sections = parseVocabRaw(text);
const count = sections.reduce((n, s) => n + s.entries.length, 0);
const out = `/* Generated by build-vocab.mjs — do not edit */\nconst VOCAB_SECTIONS = ${JSON.stringify(sections)};\n`;
fs.writeFileSync(path.join(dir, "vocab.js"), out);
console.log(`sections ${sections.length}, entries ${count} → vocab.js`);
spawnSync(process.execPath, ["build-auto-gloss.mjs"], { cwd: dir, stdio: "inherit" });
spawnSync(process.execPath, ["build-phrase-gloss.mjs"], { cwd: dir, stdio: "inherit" });
spawnSync(process.execPath, ["build-notes.mjs"], { cwd: dir, stdio: "inherit" });
spawnSync(process.execPath, ["build-tags.mjs"], { cwd: dir, stdio: "inherit" });
spawnSync(process.execPath, ["audit-notes.mjs"], { cwd: dir, stdio: "inherit" });
