/** Character / phrase fragments for auto-translating glossary Chinese → English. */
export const ZH_FRAG = {
  藝術: "art",
  藝: "art",
  術: "technique; craft",
  畫: "painting; picture",
  線: "line",
  形: "shape; form",
  色: "colour",
  光: "light",
  影: "shadow; image",
  體: "body; volume",
  面: "surface; plane",
  法: "method; technique",
  式: "style; type",
  感: "feeling; sense",
  度: "degree; level",
  性: "quality; nature",
  化: "process; -isation",
  器: "tool; vessel",
  具: "tool",
  材: "material",
  料: "material",
  質: "quality; texture",
  紋: "pattern; grain",
  筆: "brush; stroke",
  墨: "ink",
  紙: "paper",
  布: "cloth",
  木: "wood",
  石: "stone",
  金: "metal; gold",
  銀: "silver",
  銅: "copper",
  鐵: "iron",
  玻: "glass",
  陶: "ceramics",
  瓷: "porcelain",
  窯: "kiln",
  釉: "glaze",
  燒: "firing; bake",
  版: "block; plate",
  印: "print; stamp",
  攝: "photograph",
  鏡: "lens; mirror",
  像: "image",
  圖: "image; diagram",
  形: "form; shape",
  態: "state; form",
  動: "movement",
  靜: "still; static",
  寫: "write; depict",
  生: "life; raw",
  寫生: "from-life drawing",
  非彩色: "without hue; achromatic",
  黑: "black",
  白: "white",
  灰: "grey",
  彩色: "in colour",
  頂板: "top board; column abacus slab",
  圓柱: "round column",
  頂冠板: "crown plate on a column",
  研磨: "grinding",
  料: "material",
  吸附: "absorption",
  作用: "action; effect",
  催快: "accelerating",
  劑: "agent; chemical",
  丙酮: "acetone solvent",
  學院: "academy",
  派: "school; style",
  院畫: "academic salon painting",
  衛城: "citadel; acropolis",
  塑膠: "plastic",
  彩: "colour pigment",
  亞加力: "acrylic",
  壓克力: "acrylic",
  行動: "action",
  繪畫: "painting",
  加色: "additive colour",
  原理: "theory; principle",
  黏合: "bonding",
  黏接: "adhesive joining",
  黏貼: "pasting",
  鄰近: "adjacent",
  鐵鉋: "iron plane (woodworking tool)",
  早期: "early",
  樣本: "sample",
  初樣: "first proof",
  印刷: "printing",
  趨前: "advancing (colour)",
  空氣: "atmospheric",
  透視: "perspective",
  高視: "high viewpoint",
  俯視: "bird's-eye view",
  鳥瞰: "aerial view",
  天氣: "weather",
  圖: "chart; image",
  美感: "aesthetic feeling",
  經驗: "experience",
  判斷: "judgement",
  觀念: "concept; perception",
  靈敏度: "sensitivity",
  品味: "taste",
  趣味: "interest; taste",
  唯美: "aestheticist",
  主義: "movement",
  美學: "aesthetics",
  老化: "ageing",
  陶藝: "ceramics",
  噴筆: "airbrush pen",
  噴槍: "spray gun",
  冊頁: "album leaf",
  直線: "straight line",
  排列: "alignment",
  層: "layer",
  完成: "finished in one pass",
  畫法: "painting method",
  直接: "direct",
  祭壇: "altar",
  畫: "painting; picture",
  高身: "high relief",
  浮雕: "relief sculpture",
  礬紙: "alum-sized paper",
  熟紙: "sized paper (ready for painting)",
  鋁片: "aluminium plate",
  亞紅礬: "ammonium salt",
  重鉻酸銨: "ammonium dichromate",
  前後: "front and back",
  兩排: "double row",
  柱式: "column order",
  圓形: "circular",
  劇場: "theatre",
  近似: "analogous",
  類似: "similar",
  分析: "analytical",
  立體: "three-dimensional",
  解剖: "anatomy",
  成角: "angular",
  動畫: "animation",
  對比色: "contrasting colour",
  對抗色: "opposing colour",
  輪廓線: "contour line",
  留空: "reserved blank",
  古代: "ancient",
  風格: "style",
  古董: "antique object",
  古藝術品: "antiquities",
  光圈: "aperture",
  實用: "applied",
  美術: "fine/applied art",
  貼布: "appliqué fabric",
  繡法: "embroidery technique",
  補花: "patchwork floral",
  鑲飾: "inlay ornament",
  透明: "transparent",
  水彩: "watercolour",
  幼點: "fine dot",
  腐蝕: "etching corrosion",
  飛塵: "aquatint dust",
  曲線: "curved",
  變化: "variation",
  渦捲: "scroll spiral",
  圖案: "pattern",
  亞拉伯: "Arabesque",
  流動: "flowing",
  怪誕: "grotesque",
  作品: "work",
  拱形: "arch shape",
  拱門: "archway",
  古風: "archaic style",
  古風主義: "archaism",
  擬古: "neo-archaic",
  建築: "architecture",
  連接: "connecting",
  橫樑: "beam; architrave",
  白黏土: "white clay",
  陶土: "pottery clay",
  塑像: "sculpture",
  內部: "internal",
  支架: "armature support",
  骨架: "skeleton frame",
  藝術: "art",
  欣賞: "appreciation",
  評賞: "appreciation and criticism",
  批評: "criticism",
  評鑑: "critical assessment",
  評論家: "art critic",
  評論: "critique writing",
  畫廊: "art gallery",
  美術館: "art museum",
  藝術館: "art museum",
  新藝術: "Art Nouveau",
  運動: "movement",
  正稿: "finished artwork",
  畫稿: "painted draft",
  藝術作品: "artwork",
  人工: "man-made",
  製品: "artifact",
  工藝匠: "artisan craftsperson",
  傳統: "heritage tradition",
  作者版: "artist's proof print",
  畫家版: "artist's edition",
  試版: "trial proof",
  昇高: "ascender stroke",
  筆畫: "stroke",
  昇部: "ascender part (typography)",
  精製: "refined",
  瀝青粉: "asphaltum powder",
  版畫: "printmaking",
  組合: "assemblage",
  集成: "integrated",
  不對稱: "asymmetric",
  構圖: "composition",
  美術工作室: "artist's studio",
  空氣色: "atmospheric colour",
  色彩: "colour",
  拍賣: "auction",
  觀者: "viewer",
  光環: "halo",
  宗教: "religious",
  毛樣: "rough proof print",
  初印: "first impression print",
  初稿: "preliminary cartoon",
  自動: "automatic",
  對焦: "focus (camera)",
  相機: "camera",
  手製: "hand-made",
  版: "plate; block",
  直接製版: "direct stencil method",
  自動的: "automatic (process)",
  自動主義: "automatism",
  自發: "spontaneous",
  自然光: "available natural light",
  前衛: "avant-garde",
  前衛藝術: "avant-garde art"
};

export function segmentTranslate(zh) {
  let s = zh.replace(/[（(][^）)]+[）)]/g, "").trim();
  if (!s) return null;
  const keys = Object.keys(ZH_FRAG).sort((a, b) => b.length - a.length);
  let out = s;
  let changed = true;
  while (changed && /[\u4e00-\u9fff]/.test(out)) {
    changed = false;
    for (const k of keys) {
      if (out.includes(k)) {
        out = out.replaceAll(k, ` ${ZH_FRAG[k]} `);
        changed = true;
      }
    }
  }
  out = out.replace(/[\u4e00-\u9fff]+/g, " ").replace(/\s+/g, " ").trim();
  if (!out || out.length < 4) return null;
  const result = out.replace(/\s*;\s*/g, "; ").replace(/\s+/g, " ");
  if (/quality;\s*nature|method;\s*technique|painting;\s*picture|print;\s*stamp/i.test(result))
    return null;
  if ((result.match(/;/g) || []).length >= 2 && result.length < 90) return null;
  return result;
}
