window.ibKeyVocab = {
  "human-factors.html": {
    "Anthropometrics": "Measurement of human body dimensions (from Greek: anthro = people, metrics = measure)",
    "Ergonomics": "Designing for human comfort, safety, and efficiency",
    "Percentile": "Statistical value showing how a measurement compares to a population",
    "Biomechanics": "Study of movement and forces on the human body",
    "Physiological factors": "Physical characteristics affecting performance (e.g. strength, stamina)",
    "Psychological factors": "Mental processes affecting interaction (e.g. perception, memory)",
    "Static data": "Measurements when the body is still",
    "Dynamic data": "Measurements when the body is moving",
    "Inclusive design": "Designing products accessible to as many people as possible",
    "Usability": "How easy and satisfying a product is to use"
  },
  "psychological-factors.html": {
    "Input": "Light, sound, pressure, heat, taste, or smell that enters the body",
    "Sensory process": "How sensory organs detect input",
    "Brain": "Processes information and decides what to do",
    "Output": "A response or action (e.g., moving your hand away from something hot)",
    "Visibility": "Can users see it clearly? (font size, color contrast, glare)",
    "Readability": "Is the information easy to read?",
    "Screen resolution": "How sharp or blurry a display is",
    "Pitch, frequency, volume": "Sound properties that affect hearing alerts/instructions",
    "Amplitude": "Height of a sound wave; higher amplitude = louder sound",
    "Texture": "How something feels to the touch",
    "Friction": "Resistance to sliding or holding",
    "Temperature": "How hot or cold something feels",
    "Skin layers": "Epidermis, dermis, hypodermis—each senses differently",
    "Survival mechanism (taste)": "Bitter = warning; taste buds detect salty, bitter, sweet, umami, sour",
    "Emotional triggers (smell)": "Smells can spark memories and feelings; bad smells = warning"
  },
  "physiological-factors.html": {
    "Comfort": "Feeling physically or psychologically at ease",
    "Fatigue": "Physical or mental tiredness",
    "Biomechanics": "How our bodies move (joints, muscles, posture, force)",
    "Muscle Strength": "How much force we can use (changes with age!)",
    "Mechanical Advantage": "Using tools or machines to make tasks easier",
    "Torque": "A force that causes rotation (think: opening a jar)",
    "Ergonomics": "Designing for human comfort, safety, and efficiency",
    "Inclusive Design": "Designing products accessible to as many people as possible"
  },
  "resources-and-reserves.html": {
    "Resource": "Any natural material that can be used by humans (e.g., water, wood, oil, minerals)",
    "Reserve": "The known amount of a resource that can be economically and legally extracted with current technology",
    "Renewable Resource": "Can be replaced naturally in a short time (e.g., solar, wind, timber)",
    "Non-renewable Resource": "Cannot be replaced quickly (e.g., coal, oil, metals)",
    "Natural resources": "Found in nature (e.g., water, minerals, forests)",
    "Human resources": "People and their skills",
    "Physical resources": "Man-made items (e.g., machines, buildings)",
    "Energy resources": "Sources of power (e.g., fossil fuels, wind, solar)"
  },
  "waste-mitigation-strategies.html": {
    "Dematerialization": "Using less material and energy in products and processes",
    "Embodied energy": "Total energy used to make, transport, use, and dispose of a product",
    "Reuse": "Using a product again for the same or a new purpose",
    "Repair": "Fixing a product to extend its life",
    "Recycle": "Turning waste into new products",
    "Recondition": "Restoring a product to like-new condition",
    "Re-engineer": "Redesigning to improve efficiency or reduce material/energy use"
  },
  "waste-mitigation-methods.html": {
    "Product recovery": "Getting useful materials or energy back from waste",
    "Reuse": "Using products again for the same or new purpose",
    "Reduce": "Using fewer resources and less energy",
    "Optimization": "Making processes more efficient",
    "Material substitution": "Replacing materials with more sustainable options",
    "Energy efficiency": "Using less energy to do the same work",
    "Quality assurance": "Ensuring products meet standards during production",
    "Circular economy": "Keeping resources in use for as long as possible"
  },
  "batteries.html": {
    "Battery": "Device that stores chemical energy and converts it to electrical energy",
    "Anode": "The negative electrode where oxidation occurs",
    "Cathode": "The positive electrode where reduction occurs",
    "Electrolyte": "Substance that allows ions to move between electrodes",
    "Primary battery": "Single-use, not rechargeable",
    "Secondary battery": "Rechargeable battery",
    "Capacitor": "Device that stores and releases electrical energy quickly",
    "Zinc Carbon": "Standard disposable battery (AA/AAA), not rechargeable",
    "Alkaline": "Common in AA/AAA, sometimes rechargeable, more recyclable",
    "Lithium Ion": "Rechargeable, used in phones, laptops, electric cars",
    "Lead Acid": "Rechargeable, used in car engines, delivers high voltage",
    "Nickel Iron": "Invented by Edison, durable, less common",
    "Nickel Cadmium": "Rechargeable, contains toxic cadmium",
    "Nickel Metal Hydride": "Rechargeable, used in hybrid cars and electronics"
  },
  "energy-utilization.html": {
    "Energy utilization": "How energy is used, stored, and distributed",
    "Embodied energy": "Total energy used to make, transport, use, and dispose of a product",
    "Carbon footprint": "Total greenhouse gases produced by a product or activity",
    "Renewable energy": "Energy from sources that are naturally replenished (solar, wind, hydro)",
    "Non-renewable energy": "Energy from sources that can run out (coal, oil, gas, nuclear)",
    "Cradle to grave": "The full life cycle of a product, from creation to disposal",
    "Megajoule (MJ)": "A unit of energy (1 million joules)",
    "kg CO₂/kg": "Kilograms of carbon dioxide per kilogram of material"
  },
  "energy-distribution.html": {
    "Power grid": "Network for delivering electricity from producers to consumers",
    "Local generation": "Producing energy close to where it's used",
    "CHP (Combined Heat & Power)": "Plants that generate both heat and electricity for local use",
    "Embodied carbon": "Total greenhouse gases released during a product's life cycle",
    "Greenhouse gas": "Gases that trap heat in the atmosphere (CO₂, methane, etc.)",
    "Global warming potential (GWP)": "How much a gas contributes to global warming compared to CO₂"
  },
  "clean-technology.html": {
    "Clean technology": "Products, services, or processes that reduce waste and use fewer non-renewable resources",
    "Service": "Non-physical product (like banking, streaming, food delivery)",
    "Process": "How something is made or done (manufacturing, energy generation)",
    "Legislation": "Laws that require or encourage clean tech",
    "Community pressure": "When people or groups push for cleaner practices",
    "International treaty": "Agreements between countries to protect the environment",
    "Vision 2030": "Saudi Arabia's plan to diversify its economy and reduce oil dependence"
  },
  "concept-modeling.html": {
    "Conceptual model": "An idea or mental model to help understand and solve problems",
    "Ideation": "Generating lots of ideas for solutions",
    "Iteration": "Repeating and improving ideas over time",
    "Prototype": "A physical or virtual model built to test ideas",
    "Communication": "Sharing ideas with others (team, client, manufacturer)"
  },
  "graphical-modeling.html": {},
  "physical-modeling.html": {
    "Physical model": "A 3D model made to test, explore, or communicate a design",
    "Scale model": "A model that is proportionally smaller or larger than the real object",
    "Mock-up": "A scale or full-size model used to gain feedback, may have some functionality",
    "Aesthetic model": "Looks like the real product but doesn't function",
    "Prototype": "A working model that functions like the final product",
    "Instrumented model": "A prototype with sensors to collect data",
    "Fidelity": "How closely a model matches the final product (low, medium, high)"
  },
  "computer-aided-design.html": {
    "CAD": "Computer-Aided Design: using software to create, modify, analyze, or optimize a design",
    "2D modeling": "Flat drawings (length & width), e.g., Adobe Illustrator, AutoCAD",
    "3D modeling": "Digital objects with length, width, and depth, e.g., Fusion 360, SketchUp, SolidWorks",
    "Rendering": "Making a 3D model look real with lighting, textures, and shadows (e.g., Blender, 3DS Max)",
    "Surface model": "Realistic image of a product's exterior, no interior data",
    "Solid model": "Includes both exterior and interior data (volume, structure)",
    "Data model": "Organizes and structures data, often for IT systems",
    "Virtual prototyping": "Interactive digital mock-ups for testing and feedback"
  },
  "rapid-prototyping.html": {
    "Rapid prototyping": "Quickly producing a complete product (with internal detail) using digital tools",
    "Additive manufacturing": "Building up a product by adding material (e.g., 3D printing)",
    "Subtractive manufacturing": "Creating a product by removing material (e.g., milling)",
    "3D printing": "Additive process that builds objects layer by layer",
    "Milling": "Subtractive process that removes material using a rotating tool",
    "CNC": "Computer Numerical Control; machines controlled by computers (e.g., CNC router)",
    "Axis (axes)": "Directions of movement (X, Y, Z); 3-axis or 5-axis machines",
    "Filament": "Material (often plastic) used in 3D printing",
    "Resin": "Liquid material hardened by light in some 3D printers"
  },
  "advanced-cad-tech.html": {
    "Bottom-up design": "Creating all parts separately, then assembling (e.g., piston)",
    "Top-down design": "Designing the overall shape first, then fitting components inside (e.g., car body)",
    "Digital humans": "Computer models simulating human mechanics/biology for testing (e.g., pilot reach)",
    "Motion capture": "Recording real human movement for animation (e.g., Andy Serkis as Gollum)",
    "Haptic technology": "Tech that simulates touch/force feedback (e.g., VR suits, game controllers)",
    "Virtual reality (VR)": "Simulating real situations on screen, interactively",
    "Animation": "Linking graphics to simulate motion or process",
    "Finite element analysis (FEA)": "Simulating stresses/forces in products using CAD"
  },
  "additive-manufacturing-tech.html": {
    "Stereolithography (SLA)": "Additive process using UV laser to harden resin layer by layer",
    "Laminated Object Manufacturing (LOM)": "Laser cuts and stacks sheets of material to build up an object",
    "Fused Deposition Modeling (FDM)": "3D printing technique that melts and deposits layers of material (e.g., plastic, concrete)",
    "Selective Laser Sintering (SLS)": "Laser fuses powder particles into a solid 3D shape",
    "Filament": "Material (often plastic) melted in FDM 3D printing",
    "Resin": "Liquid material hardened by light in SLA 3D printing",
    "Powder": "Fine material fused by laser in SLS",
    "Layers": "Thin slices added one at a time to build up a 3D object"
  },
  "properties-of-materials.html": {
    "Density": "Mass per unit volume (g/cm³ or kg/m³)",
    "Electrical resistivity": "How well a material resists electrical flow",
    "Thermal conductivity": "How well a material conducts heat",
    "Thermal expansion": "How much a material expands when heated",
    "Hardness": "Resistance to scratching or penetration",
    "Tensile strength": "Resistance to pulling forces",
    "Compression": "Resistance to being squashed",
    "Stiffness": "Resistance to bending or deflection",
    "Toughness": "Resistance to crack propagation",
    "Ductility": "Ability to be drawn into wire or extended shape",
    "Aesthetics": "How a material looks, feels, smells, or tastes"
  },
  "smart-materials.html": {},
  "material-graphs-selection.html": {},
  "metals.html": {},
  "alloys.html": {},
  "timber.html": {},
  "glass.html": {},
  "plastics.html": {},
  "textiles.html": {},
  "composites.html": {},
  "scales-of-production.html": {},
  "manufacturing-processes.html": {},
  "shaping-and-joining.html": {},
  "production-systems.html": {},
  "robots-in-automated-production.html": {},
  "invention-and-intellectual-property.html": {
    "Invention": "Discovering a new principle that leads to a novel product",
    "Motivators for invention": "Personal interest, constructive discontent, money, scientific curiosity, necessity",
    "Lone inventor": "Someone working (often alone) on a novel product, sometimes isolated",
    "Intellectual property (IP)": "Legal rights for creations of the mind (inventions, designs, etc.)",
    "Patent": "Government-granted right to make/sell an invention for a set time",
    "Copyright": "Legal right for creators to control use/distribution of their work",
    "Trademark": "Symbol, word, or phrase legally registered to represent a company/product",
    "Public domain": "When copyright expires or is given up; anyone can use the work",
    "First to market": "First product of its type released; can make the most money",
    "Shelf technology": "Tech that's developed but not released until later"
  },
  "innovation-and-diffusion.html": {},
  "strategies-for-innovation.html": {},
  "stakeholders-in-innovation.html": {},
  "product-life-cycles.html": {},
  "product-versions-and-strategies.html": {},
  "rogers-characteristics-of-innovation.html": {},
  "innovation-design-and-marketing-specifications.html": {},
  "characteristics-of-classic-design.html": {},
  "classic-designs-examples.html": {},
  "classic-design-form-and-function.html": {}
};
