// Chinese (HK) translations for key vocab — shown on click, not English definitions
window.ibKeyVocabZh = {
  "2D modeling": "二維建模",
  "3D modeling": "三維建模",
  "3D printing": "三維打印",
  "5S methodology": "5S 管理",
  "A/B testing": "A/B 測試",
  "Accessibility": "無障礙",
  "Accountability": "問責",
  "Actor": "角色",
  "Additive manufacturing": "增材製造",
  "Adhesive bonding": "膠合",
  "Aesthetic model": "外觀模型",
  "Aesthetics": "美學",
  "Affordance": "可操作性",
  "Alkaline": "鹼性電池",
  "Alloy": "合金",
  "Amplitude": "振幅",
  "Animation": "動畫",
  "Anisotropic": "各向異性",
  "Anode": "負極",
  "Anthropometrics": "人體測量學",
  "Ashby chart": "阿什比圖",
  "Assembly": "裝配",
  "Assistive technology": "輔助科技",
  "Automation": "自動化",
  "Axis (axes)": "軸",
  "B2B vs B2C": "企對企／企對消",
  "Backward compatibility": "向下兼容",
  "Balance": "平衡",
  "Barrier": "障礙",
  "Batch production": "批量生產",
  "Battery": "電池",
  "Bias": "偏誤",
  "Biodegradable plastic": "可生物分解塑料",
  "Biomechanics": "生物力學",
  "Biomimicry": "仿生學",
  "Borosilicate glass": "硼矽玻璃",
  "Bottleneck": "瓶頸",
  "Bottom-up design": "自下而上設計",
  "Brain": "大腦",
  "Brainstorming": "腦力激盪",
  "Brand": "品牌",
  "Brand equity": "品牌資產",
  "Brand experience": "品牌體驗",
  "Brand extension": "品牌延伸",
  "Brand identity": "品牌識別",
  "Brand loyalty": "品牌忠誠度",
  "Brand recognition": "品牌識別度",
  "Brass": "黃銅",
  "Brazing / soldering": "釬焊／軟焊",
  "Break-even analysis": "收支平衡分析",
  "Break-even point": "收支平衡點",
  "Breakthrough": "突破",
  "Breathability": "透氣性",
  "Brittleness": "脆性",
  "Bronze": "青銅",
  "Brundtland definition": "Brundtland 定義",
  "Buffer stock": "緩衝庫存",
  "CAD": "電腦輔助設計",
  "CAD/CAM integration": "CAD/CAM 集成",
  "CHP (Combined Heat & Power)": "熱電聯產",
  "CNC": "數控加工",
  "Capacitor": "電容器",
  "Capital investment": "資本投資",
  "Carbon fibre reinforced polymer (CFRP)": "碳纖維強化聚合物",
  "Carbon footprint": "碳足跡",
  "Carbon tax": "碳稅",
  "Casting": "鑄造",
  "Cathode": "正極",
  "Cellular manufacturing": "單元式生產",
  "Certification": "認證",
  "Choose low-impact materials": "選擇低影響材料",
  "Circular economy": "循環經濟",
  "Clean tech": "潔淨科技",
  "Clean technology": "潔淨科技",
  "Closed innovation": "封閉式創新",
  "Co-design": "共同設計",
  "Cobot (collaborative robot)": "協作機械人",
  "Coke bottle": "可口可樂瓶",
  "Comfort": "舒適",
  "Communication": "溝通",
  "Community pressure": "社會壓力",
  "Compatibility": "兼容性",
  "Competition": "競爭",
  "Competitive advantage": "競爭優勢",
  "Competitive analysis": "競爭分析",
  "Competitor benchmarking": "競爭對標",
  "Complexity": "複雜性",
  "Compliance": "合規",
  "Composite material": "複合材料",
  "Compostable": "可堆肥分解",
  "Compression": "抗壓",
  "Computer-integrated manufacturing (CIM)": "計算機集成製造",
  "Conceptual model": "概念模型",
  "Conductivity": "導電／導熱性",
  "Conflict of interest": "利益衝突",
  "Consumer behaviour": "消費行為",
  "Consumer demand": "消費者需求",
  "Consumer responsibility": "消費者責任",
  "Context of use": "使用情境",
  "Contextual inquiry": "情境調查",
  "Continuous flow": "連續流",
  "Continuous improvement (Kaizen)": "持續改善",
  "Continuous production": "連續生產",
  "Controlled vs natural setting": "受控與自然環境",
  "Convention": "慣例",
  "Copyright": "版權",
  "Core product": "核心產品",
  "Corporate social responsibility (CSR)": "企業社會責任",
  "Corrosion": "腐蝕",
  "Cost savings": "成本節省",
  "Cost-benefit analysis": "成本效益分析",
  "Counterfeit": "假冒產品",
  "Cradle to cradle": "從搖籃到搖籃",
  "Cradle to grave": "由搖籃到墳墓",
  "Cultural difference": "文化差異",
  "Cultural impact": "文化影響",
  "Current state map": "現狀圖",
  "Customer insight": "客戶洞察",
  "Customer retention": "客戶保留",
  "Customisation": "定制",
  "Cycle time": "週期時間",
  "Dashevsky's principles": "Dashevsky 五原則",
  "Data model": "數據模型",
  "Data triangulation": "數據三角驗證",
  "Data-driven decisions": "數據驅動決策",
  "Decline stage": "衰退期",
  "Defect rate": "缺陷率",
  "Defect waste": "缺陷浪費",
  "Degrees of freedom": "自由度",
  "Delight factor": "驚喜因素",
  "Demand": "需求",
  "Demand uncertainty": "需求不確定性",
  "Dematerialization": "減材化",
  "Demographic": "人口統計",
  "Density": "密度",
  "Design brief": "設計簡報",
  "Design canon": "設計經典",
  "Design constraint": "設計限制",
  "Design for disassembly": "可拆解設計",
  "Design for environment (DfE)": "環境設計",
  "Design for longevity": "耐久設計",
  "Design for reuse/recycling": "重用／回收設計",
  "Design heritage": "設計傳承",
  "Design specification": "設計規格",
  "Design thinking": "設計思維",
  "Designer responsibility": "設計師責任",
  "Desirability": "渴望度",
  "Dieter Rams": "Dieter Rams",
  "Diffusion": "擴散",
  "Digital humans": "數碼人體模型",
  "Digital twin": "數字孿生",
  "Dimensioning": "尺寸標註",
  "Disruptive innovation": "顛覆性創新",
  "Diverse users": "多元用戶",
  "Downtime": "停機時間",
  "Driver of green design": "綠色設計驅動力",
  "Ductility": "延展性",
  "Durability": "耐用性",
  "Duralumin": "硬鋁",
  "Dynamic data": "動態數據",
  "Eames Lounge Chair": "Eames 躺椅",
  "Early adopter": "早期採用者",
  "Eco-design": "生態設計",
  "Eco-innovation": "生態創新",
  "Ecological footprint": "生態足跡",
  "Economic viability": "經濟可行性",
  "Economies of scale": "規模經濟",
  "Edge case": "極端情況",
  "Effectiveness": "有效性",
  "Efficiency": "效率",
  "Electrical resistivity": "電阻率",
  "Electroluminescent": "電致發光",
  "Electrolyte": "電解質",
  "Embodied carbon": "隱含碳",
  "Embodied energy": "隱含能源",
  "Emotional branding": "情感品牌",
  "Emotional design": "情感設計",
  "Emotional triggers (smell)": "氣味情緒觸發",
  "Empathy": "同理心",
  "Empowerment": "授權",
  "End effector": "末端執行器",
  "End user": "終端用戶",
  "End-of-life strategy": "報廢策略",
  "Energy efficiency": "能源效益",
  "Energy mix": "能源組合",
  "Energy resources": "能源資源",
  "Energy return on investment (EROI)": "能源投資回報",
  "Energy sustainability": "能源可持續性",
  "Energy utilization": "能源運用",
  "Engagement": "參與度",
  "Environmental impact assessment": "環境影響評估",
  "Environmental legislation": "環境法例",
  "Equitable use": "公平使用",
  "Ergonomics": "人體工學",
  "Error rate": "錯誤率",
  "Ethical design": "道德設計",
  "Extended producer responsibility": "延伸生產者責任",
  "Extension strategy": "延伸策略",
  "Extrusion": "擠出",
  "Fatigue": "疲勞",
  "Feasibility": "可行性",
  "Feedback loop": "反饋循環",
  "Ferrous metal": "黑色金屬",
  "Fidelity": "逼真度",
  "Field testing": "現場測試",
  "Filament": "絲材",
  "Finishing": "表面處理",
  "Finite element analysis (FEA)": "有限元分析",
  "Finite resources": "有限資源",
  "First to market": "率先上市",
  "First-angle projection": "第一角法投影",
  "Fixed costs": "固定成本",
  "Fixed-position layout": "固定位置佈局",
  "Flexible manufacturing system (FMS)": "柔性製造系統",
  "Focus group": "焦點小組",
  "Forging": "鍛造",
  "Form follows function": "形式追隨功能",
  "Forming": "成型",
  "Friction": "摩擦力",
  "Frugal innovation": "節約式創新",
  "Functionality": "功能性",
  "Fused Deposition Modeling (FDM)": "熔融沉積成型",
  "Future state map": "未來狀態圖",
  "GFRP": "玻璃纖維強化塑料",
  "Gap analysis": "差距分析",
  "Gemba": "現場",
  "Global branding": "全球品牌",
  "Global warming potential (GWP)": "全球暖化潛勢",
  "Government role": "政府角色",
  "Grain": "木紋",
  "Green design": "綠色設計",
  "Green patent": "綠色專利",
  "Greenhouse gas": "溫室氣體",
  "Greenwashing": "漂綠",
  "Grid decarbonisation": "電網脫碳",
  "Growth stage": "成長期",
  "Haptic technology": "觸覺技術",
  "Hardness": "硬度",
  "Hardwood": "硬木",
  "Heuristic evaluation": "啟發式評估",
  "High-fidelity prototype": "高保真原型",
  "Holistic approach": "整體方法",
  "Honest construction": "誠實結構",
  "Human resources": "人力資源",
  "Hydrophobic / hydrophilic": "疏水／親水",
  "ISO 9001": "ISO 9001",
  "ISO standards": "ISO 標準",
  "Iconic design": "標誌性設計",
  "Ideation": "構思",
  "Inclusive Design": "共融設計",
  "Inclusive design": "共融設計",
  "Incremental innovation": "漸進式創新",
  "Industrial robot": "工業機械人",
  "Information flow": "信息流",
  "Injection moulding": "注塑成型",
  "Innovation": "創新",
  "Innovation-decision process": "創新決策過程",
  "Input": "輸入（感官刺激）",
  "Instrumented model": "儀器化模型",
  "Intellectual property (IP)": "知識產權",
  "Interchangeable parts": "互換零件",
  "Interference fit": "干涉配合",
  "Intergenerational equity": "代際公平",
  "International treaty": "國際條約",
  "Introduction stage": "導入期",
  "Invention": "發明",
  "Inventory reduction": "庫存減少",
  "Investor": "投資者",
  "Investor pressure": "投資者壓力",
  "Isometric drawing": "等角投影圖",
  "Iteration": "迭代",
  "Iterative design": "迭代設計",
  "Just in Case (JIC)": "備貨生產",
  "Just in Time (JIT)": "準時生產",
  "Kaizen": "改善",
  "Kanban": "看板",
  "Kerf": "鋸縫",
  "Knit": "針織",
  "Knot": "節疤",
  "Labeling": "標籤",
  "Laggard": "落伍者",
  "Laminated Object Manufacturing (LOM)": "疊層物體製造",
  "Laminated glass": "夾層玻璃",
  "Launch strategy": "上市策略",
  "Lay-up": "鋪層",
  "Layers": "層",
  "Lead Acid": "鉛酸電池",
  "Lead time": "前置時間",
  "Lead user": "領先用戶",
  "Lean production": "精益生產",
  "Leapfrog technology": "跨越式技術",
  "Learnability": "易學性",
  "Legislation": "法例",
  "Life cycle assessment (LCA)": "生命週期評估",
  "Lithium Ion": "鋰離子電池",
  "Local generation": "本地發電",
  "Localisation": "本地化",
  "London Underground map": "倫敦地鐵圖",
  "Lone inventor": "獨立發明家",
  "Long-term satisfaction": "長期滿意度",
  "Low-fidelity prototype": "低保真原型",
  "Low-impact manufacturing": "低影響製造",
  "MDF": "中密度纖維板",
  "Machining": "機械加工",
  "Malleability": "展性",
  "Manufacturer": "製造商",
  "Manufacturer responsibility": "製造商責任",
  "Market": "市場",
  "Market opportunity": "市場機會",
  "Market research": "市場研究",
  "Market saturation": "市場飽和",
  "Market sector": "市場行業",
  "Market segment": "市場細分",
  "Market segmentation": "市場細分",
  "Marketing mix (4 Ps)": "市場營銷組合（4P）",
  "Marketing specification": "市場規格",
  "Mass customisation": "大量定制",
  "Mass market": "大眾市場",
  "Mass production": "大量生產",
  "Material flow": "物料流",
  "Material flow analysis": "物料流分析",
  "Material selection chart": "材料選擇圖表",
  "Material substitution": "物料替代",
  "Matrix": "基質",
  "Maturity stage": "成熟期",
  "Mechanical Advantage": "機械優勢",
  "Mechanical fastening": "機械連接",
  "Megajoule (MJ)": "百萬焦耳",
  "Mental model": "心智模型",
  "Milling": "銑削",
  "Minimalism": "極簡主義",
  "Minimise material use": "減少物料使用",
  "Mock-up": "模型樣板",
  "Moderator": "主持人",
  "Modular design": "模組化設計",
  "Modularity": "模組化",
  "Monomer": "單體",
  "Motion capture": "動作捕捉",
  "Motivators for invention": "發明動機",
  "Moulding": "—",
  "Muda": "浪費",
  "Muscle Strength": "肌力",
  "Natural fibre": "天然纖維",
  "Natural mapping": "自然映射",
  "Natural resources": "天然資源",
  "Net zero": "淨零排放",
  "Niche market": "利基市場",
  "Nickel Cadmium": "鎳鎘電池",
  "Nickel Iron": "鎳鐵電池",
  "Nickel Metal Hydride": "鎳氫電池",
  "Non-ferrous metal": "有色金屬",
  "Non-renewable Resource": "不可再生資源",
  "Non-renewable energy": "不可再生能源",
  "Non-value-added activity": "非增值活動",
  "Non-woven": "非織造",
  "Observability": "可觀察性",
  "Obsolescence": "過時",
  "Obsolescence risk": "過時風險",
  "One-off production": "單件生產",
  "Online survey": "網上問卷",
  "Open innovation": "開放式創新",
  "Optimization": "優化",
  "Optimum": "最優選擇",
  "Ornamentation": "裝飾",
  "Orthographic projection": "正投影",
  "Output": "輸出（反應）",
  "Overconsumption": "過度消費",
  "Overproduction waste": "過量生產浪費",
  "PDCA cycle": "PDCA 循環",
  "Packaging design": "包裝設計",
  "Paradigm shift": "範式轉移",
  "Participatory design": "參與式設計",
  "Passive design": "被動式設計",
  "Patent": "專利",
  "Penetration pricing": "滲透定價",
  "Percentile": "百分位數",
  "Performance index": "性能指數",
  "Persona": "用戶角色",
  "Photochromic": "光致變色",
  "Physical model": "實體模型",
  "Physical resources": "物質資源",
  "Physiological factors": "生理因素",
  "Pick and place": "拾放",
  "Piezoelectric": "壓電",
  "Pilot launch": "試點上市",
  "Pitch, frequency, volume": "音調、頻率、音量",
  "Place": "渠道",
  "Planned obsolescence": "計劃性報廢",
  "Platform product": "平台產品",
  "Plywood": "夾板",
  "Pollution": "污染",
  "Polymer": "聚合物",
  "Population stereotype": "群體刻板印象",
  "Positioning": "定位",
  "Powder": "粉末",
  "Power grid": "電網",
  "Preventive maintenance": "預防性維護",
  "Price": "價格",
  "Primary battery": "一次性電池",
  "Primary data": "一手數據",
  "Primary research": "一手研究",
  "Process": "流程",
  "Process layout": "工藝佈局",
  "Product": "產品",
  "Product layout": "產品佈局",
  "Product life cycle": "產品生命週期",
  "Product life cycle (PLC)": "產品生命週期",
  "Product recovery": "產品回收",
  "Product versioning": "產品版本化",
  "Profit margin": "利潤率",
  "Promotion": "推廣",
  "Proportion": "比例",
  "Prototype": "原型",
  "Prototype testing": "原型測試",
  "Psychographic": "心理統計",
  "Psychological factors": "心理因素",
  "Public domain": "公有領域",
  "Pull production": "拉式生產",
  "Pull system": "拉式系統",
  "Qualitative research": "定性研究",
  "Quality assurance": "品質保證",
  "Quality assurance (QA)": "質量保證",
  "Quality control (QC)": "質量控制",
  "Quality of materials": "材料品質",
  "Quantitative research": "定量研究",
  "Questionnaire": "問卷",
  "Radical innovation": "顛覆式創新",
  "Random sampling": "隨機抽樣",
  "Rapid prototyping": "快速原型",
  "Re-engineer": "重新設計",
  "Readability": "可讀性",
  "Real-time monitoring": "實時監控",
  "Recondition": "翻新",
  "Recording": "錄影",
  "Recyclability": "可回收性",
  "Recycle": "回收",
  "Reduce": "減少使用",
  "Reduce energy in use": "減少使用能源",
  "Reduced lead time": "縮短前置時間",
  "Refurbishment": "翻新",
  "Regulation": "法規",
  "Regulator": "監管機構",
  "Regulatory pressure": "監管壓力",
  "Reinforcement": "增強物",
  "Relative advantage": "相對優勢",
  "Rendering": "渲染",
  "Renewable Resource": "可再生資源",
  "Renewable energy": "可再生能源",
  "Renewable materials": "可再生材料",
  "Repair": "維修",
  "Repair culture": "維修文化",
  "Reputation": "聲譽",
  "Reserve": "儲量",
  "Resin": "樹脂",
  "Resource": "資源",
  "Respect for people": "尊重人",
  "Return on investment (ROI)": "投資回報率",
  "Reuse": "重用",
  "Risk": "風險",
  "Riveting": "鉚接",
  "RoHS": "RoHS 指令",
  "Rogers' diffusion theory": "Rogers 擴散理論",
  "Root cause analysis": "根本原因分析",
  "S-curve": "S 形曲線",
  "SCAMPER": "SCAMPER 創意思維法",
  "SDGs": "可持續發展目標",
  "Safety stock": "安全庫存",
  "Sampling": "抽樣",
  "Satisfaction": "滿意度",
  "Scale model": "比例模型",
  "Screen resolution": "螢幕解像度",
  "Seasoning": "乾燥處理",
  "Secondary battery": "可充電電池",
  "Secondary data": "二手數據",
  "Secondary research": "二手研究",
  "Section view": "剖視圖",
  "Selective Laser Sintering (SLS)": "選擇性激光燒結",
  "Sensory process": "感官過程",
  "Service": "服務",
  "Set in order (Seiton)": "整頓",
  "Setup time": "設置時間",
  "Seven wastes (TIMWOOD)": "七大浪費",
  "Shape memory alloy": "形狀記憶合金",
  "Sharing economy": "共享經濟",
  "Shelf appeal": "貨架吸引力",
  "Shelf technology": "儲架技術",
  "Signifier": "意符",
  "Simplicity": "簡約",
  "Skilled workforce": "技術工人",
  "Skimming pricing": "撇脂定價",
  "Skin layers": "皮膚層",
  "Smart grid": "智能電網",
  "Smart material": "智能材料",
  "Social innovation": "社會創新",
  "Soda-lime glass": "鈉鈣玻璃",
  "Softwood": "軟木",
  "Solder": "焊料",
  "Solid model": "實體模型",
  "Sort (Seiri)": "整理",
  "Stainless steel": "不鏽鋼",
  "Stakeholder": "持份者",
  "Stakeholder interview": "持份者訪談",
  "Standard operating procedure (SOP)": "標準作業程序",
  "Standardization": "標準化",
  "Static data": "靜態數據",
  "Statistical process control (SPC)": "統計過程控制",
  "Stereolithography (SLA)": "立體光刻",
  "Stiffness": "剛度",
  "Stockholding cost": "持貨成本",
  "Storyboard": "故事板",
  "Subtractive manufacturing": "減材製造",
  "Success criteria": "成功標準",
  "Supplier reliability": "供應商可靠性",
  "Supply": "供應",
  "Supply chain": "供應鏈",
  "Supply chain risk": "供應鏈風險",
  "Surface model": "曲面模型",
  "Survival mechanism (taste)": "味覺求生機制",
  "Sustain (Shitsuke)": "素養",
  "Sustainable consumption": "可持續消費",
  "Sustainable design": "可持續設計",
  "Sustainable development": "可持續發展",
  "Sustainable innovation": "可持續創新",
  "Sustainable sourcing": "可持續採購",
  "Synthetic fibre": "合成纖維",
  "Systems thinking": "系統思維",
  "Take-back scheme": "回收計劃",
  "Takt time": "節拍時間",
  "Target market": "目標市場",
  "Task analysis": "任務分析",
  "Task script": "任務腳本",
  "Team-based improvement": "團隊改善",
  "Technical drawing": "工程製圖",
  "Technology transfer": "技術轉移",
  "Temperature": "溫度",
  "Tempered glass": "強化玻璃",
  "Ten principles of good design": "優良設計十原則",
  "Tensile strength": "抗拉強度",
  "Texture": "質感",
  "Thermal conductivity": "導熱性",
  "Thermal expansion": "熱膨脹",
  "Thermochromic": "熱致變色",
  "Thermoplastic": "熱塑性塑料",
  "Thermoset": "熱固性塑料",
  "Think-aloud protocol": "出聲思考法",
  "Third-angle projection": "第三角法投影",
  "Throughput": "產出率",
  "Timeless design": "永恆設計",
  "Tolerance": "公差",
  "Tolerance limits": "公差限",
  "Top-down design": "自上而下設計",
  "Torque": "扭矩",
  "Total cost of ownership": "總擁有成本",
  "Toughness": "韌度",
  "Toxicity reduction": "毒性減少",
  "Trade-off": "取捨",
  "Trademark": "商標",
  "Transparency": "透明度",
  "Trend analysis": "趨勢分析",
  "Trialability": "可試用性",
  "Triple bottom line": "三重底線",
  "Unboxing experience": "開箱體驗",
  "Unique selling point (USP)": "獨特賣點",
  "Unit cost": "單位成本",
  "Unity": "統一",
  "Universal design": "通用設計",
  "Upgrade path": "升級路徑",
  "Usability": "可用性",
  "Usability lab": "可用性實驗室",
  "Use case": "使用案例",
  "User experience (UX)": "用戶體驗",
  "User need": "用戶需求",
  "User scenario": "用戶情境",
  "User-centered design (UCD)": "以用戶為中心的設計",
  "Value proposition": "價值主張",
  "Value stream map (VSM)": "價值流圖",
  "Value-added activity": "增值活動",
  "Variable costs": "可變成本",
  "Virtual prototyping": "虛擬原型",
  "Virtual reality (VR)": "虛擬實境",
  "Visibility": "可見度",
  "Vision 2030": "2030 願景",
  "Visual hierarchy": "視覺層次",
  "WEEE directive": "WEEE 指令",
  "Waiting time": "等待時間",
  "Waste of waiting": "等待浪費",
  "Weave": "編織",
  "Weight reduction": "減重",
  "Welding": "焊接",
  "Welding robot": "焊接機械人",
  "Wizard of Oz testing": "綠野仙踪測試",
  "Work hardening": "加工硬化",
  "Workflow analysis": "工作流程分析",
  "Zinc Carbon": "鋅碳電池",
  "kg CO₂/kg": "每公斤二氧化碳"
};
