// Chinese (HK) translations for key vocab — shown on click, not English definitions
window.ibKeyVocabZh = {
  "Anthropometrics": "人體測量學",
  "Ergonomics": "人體工學",
  "Percentile": "百分位數",
  "Biomechanics": "生物力學",
  "Physiological factors": "生理因素",
  "Psychological factors": "心理因素",
  "Static data": "靜態數據",
  "Dynamic data": "動態數據",
  "Inclusive design": "共融設計",
  "Inclusive Design": "共融設計",
  "Usability": "可用性",
  "Input": "輸入（感官刺激）",
  "Sensory process": "感官過程",
  "Brain": "大腦",
  "Output": "輸出（反應）",
  "Visibility": "可見度",
  "Readability": "可讀性",
  "Screen resolution": "螢幕解像度",
  "Pitch, frequency, volume": "音調、頻率、音量",
  "Amplitude": "振幅",
  "Texture": "質感",
  "Friction": "摩擦力",
  "Temperature": "溫度",
  "Skin layers": "皮膚層",
  "Survival mechanism (taste)": "味覺求生機制",
  "Emotional triggers (smell)": "氣味情緒觸發",
  "Comfort": "舒適",
  "Fatigue": "疲勞",
  "Muscle Strength": "肌力",
  "Mechanical Advantage": "機械優勢",
  "Torque": "扭矩",
  "Resource": "資源",
  "Reserve": "儲量",
  "Renewable Resource": "可再生資源",
  "Non-renewable Resource": "不可再生資源",
  "Natural resources": "天然資源",
  "Human resources": "人力資源",
  "Physical resources": "物質資源",
  "Energy resources": "能源資源",
  "Dematerialization": "減材化",
  "Embodied energy": "隱含能源",
  "Reuse": "重用",
  "Repair": "維修",
  "Recycle": "回收",
  "Recondition": "翻新",
  "Re-engineer": "重新設計",
  "Product recovery": "產品回收",
  "Reduce": "減少使用",
  "Optimization": "優化",
  "Material substitution": "物料替代",
  "Energy efficiency": "能源效益",
  "Quality assurance": "品質保證",
  "Circular economy": "循環經濟",
  "Battery": "電池",
  "Anode": "負極",
  "Cathode": "正極",
  "Electrolyte": "電解質",
  "Primary battery": "一次性電池",
  "Secondary battery": "可充電電池",
  "Capacitor": "電容器",
  "Zinc Carbon": "鋅碳電池",
  "Alkaline": "鹼性電池",
  "Lithium Ion": "鋰離子電池",
  "Lead Acid": "鉛酸電池",
  "Nickel Iron": "鎳鐵電池",
  "Nickel Cadmium": "鎳鎘電池",
  "Nickel Metal Hydride": "鎳氫電池",
  "Energy utilization": "能源運用",
  "Carbon footprint": "碳足跡",
  "Renewable energy": "可再生能源",
  "Non-renewable energy": "不可再生能源",
  "Cradle to grave": "由搖籃到墳墓",
  "Megajoule (MJ)": "百萬焦耳",
  "kg CO₂/kg": "每公斤二氧化碳",
  "Power grid": "電網",
  "Local generation": "本地發電",
  "CHP (Combined Heat & Power)": "熱電聯產",
  "Embodied carbon": "隱含碳",
  "Greenhouse gas": "溫室氣體",
  "Global warming potential (GWP)": "全球暖化潛勢",
  "Clean technology": "潔淨科技",
  "Service": "服務",
  "Process": "流程",
  "Legislation": "法例",
  "Community pressure": "社會壓力",
  "International treaty": "國際條約",
  "Vision 2030": "2030 願景",
  "Conceptual model": "概念模型",
  "Ideation": "構思",
  "Iteration": "迭代",
  "Prototype": "原型",
  "Communication": "溝通",
  "Physical model": "實體模型",
  "Scale model": "比例模型",
  "Mock-up": "模型樣板",
  "Aesthetic model": "外觀模型",
  "Instrumented model": "儀器化模型",
  "Fidelity": "逼真度",
  "CAD": "電腦輔助設計",
  "2D modeling": "二維建模",
  "3D modeling": "三維建模",
  "Rendering": "渲染",
  "Surface model": "曲面模型",
  "Solid model": "實體模型",
  "Data model": "數據模型",
  "Virtual prototyping": "虛擬原型",
  "Rapid prototyping": "快速原型",
  "Additive manufacturing": "增材製造",
  "Subtractive manufacturing": "減材製造",
  "3D printing": "三維打印",
  "Milling": "銑削",
  "CNC": "數控加工",
  "Axis (axes)": "軸",
  "Filament": "絲材",
  "Resin": "樹脂",
  "Bottom-up design": "自下而上設計",
  "Top-down design": "自上而下設計",
  "Digital humans": "數碼人體模型",
  "Motion capture": "動作捕捉",
  "Haptic technology": "觸覺技術",
  "Virtual reality (VR)": "虛擬實境",
  "Animation": "動畫",
  "Finite element analysis (FEA)": "有限元分析",
  "Stereolithography (SLA)": "立體光刻",
  "Laminated Object Manufacturing (LOM)": "疊層物體製造",
  "Fused Deposition Modeling (FDM)": "熔融沉積成型",
  "Selective Laser Sintering (SLS)": "選擇性激光燒結",
  "Powder": "粉末",
  "Layers": "層",
  "Density": "密度",
  "Electrical resistivity": "電阻率",
  "Thermal conductivity": "導熱性",
  "Thermal expansion": "熱膨脹",
  "Hardness": "硬度",
  "Tensile strength": "抗拉強度",
  "Compression": "抗壓",
  "Stiffness": "剛度",
  "Toughness": "韌度",
  "Ductility": "延展性",
  "Aesthetics": "美學",
  "Invention": "發明",
  "Motivators for invention": "發明動機",
  "Lone inventor": "獨立發明家",
  "Intellectual property (IP)": "知識產權",
  "Patent": "專利",
  "Copyright": "版權",
  "Trademark": "商標",
  "Public domain": "公有領域",
  "First to market": "率先上市",
  "Shelf technology": "儲架技術"
};
