/* Auto-generated: EN/NE/UR strings for part2.html — run node tools/emit-page-bundles.mjs to refresh */
(function () {
  if (!window.SBA_i18n) return;
  window.SBA_i18n.mergeStrings({
    "doc.title.part2": { en: "Part 2 · Requirements & portfolio — VA SBA", ne: "भाग २ · आवश्यकता र पोर्टफोलियो — VA SBA", ur: "حصہ ۲ · ضروریات اور پورٹ فولیو — VA SBA" },
    "p2.b1": { en: "Encourage personal themes; visual and textual materials should include explanation or critical comment.", ne: "व्यक्तिगत विषयवस्तु प्रोत्साहन; दृश्य र लिखित सामग्रीमा व्याख्या वा आलोचनात्मक टिप्पणी।", ur: "ذاتی موضوعات کی حوصلہ افزائی؛ بصری و تحریری مواد میں وضاحت یا تنقیدی تبصرہ۔" },
    "p2.b2": { en: "Research and appreciation should reflect <strong>real progress</strong> during portfolio building; acknowledge all sources.", ne: "अनुसन्धान र प्रशंसाले पोर्टफोलियो बनाउँदा <strong>वास्तविक प्रगति</strong> देखाउनुपर्छ; सबै स्रोत उल्लेख गर्नुहोस्।", ur: "تحقیق و ستائش پورٹ فولیو بناتے وقت <strong>حقیقی پیش رفت</strong> دکھائے؛ تمام ذرائع کا حوالہ۔" },
    "p2.b3": { en: "Research Workbook should show: idea generation, theme exploration, multi-cultural context in appreciation, influence of artists on work, media experiments, and reflection / refinement.", ne: "कार्यपुस्तिकामा: विचार उत्पादन, विषयवस्तु अन्वेषण, बहुसांस्कृतिक संदर्भ, कलाकारको प्रभाव, माध्यम प्रयोग, पुनर्विचार / परिष्करण।", ur: "ورک بک میں: خیال پیدا کرنا، موضوع کی کھوج، کثیر ثقافتی سیاق، فنکاروں کا اثر، ذریعے کے تجربے، غور / درستگی۔" },
    "p2.h1": { en: "Part 2 · Requirements &amp; portfolio", ne: "भाग २ · आवश्यकता र पोर्टफोलियो", ur: "حصہ ۲ · ضروریات اور پورٹ فولیو" },
    "p2.h_build": { en: "Building the portfolio (2.3)", ne: "पोर्टफोलियो निर्माण (२.३)", ur: "پورٹ فولیو کی تعمیر (۲.۳)" },
    "p2.h_core": { en: "Core requirement", ne: "मुख्य आवश्यकता", ur: "بنیادی ضرورت" },
    "p2.h_mod": { en: "Research Workbook — moderation sample", ne: "अनुसन्धान कार्यपुस्तिका — मध्यस्थताको नमूना", ur: "تحقیقی ورک بک — معتدلی کے نمونے" },
    "p2.h_special": { en: "Transfer students, repeaters, private candidates", ne: "स्थानान्तरण, दोहोर्याउने, निजी उम्मेदवार", ur: "منتقلی، دہرانے والے، نجی امیدوار" },
    "p2.h_theme": { en: "Theme and genres", ne: "विषयवस्तु र विधाहरू", ur: "موضوع اور اصناف" },
    "p2.lead": { en: "Chapter 2.1–2.3 — what to submit, how to build the portfolio, and special rules for transfer students, repeaters and private candidates.", ne: "अध्याय २.१–२.३ — के पेश गर्ने, पोर्टफोलियो कसरी बनाउने, र स्थानान्तरण, दोहोर्याउने र निजी उम्मेदवारका नियमहरू।", ur: "باب ۲.۱–۲.۳ — کیا جمع کرانا ہے، پورٹ فولیو کیسے بنانا ہے، اور منتقلی، دہرانے والے اور نجی امیدواروں کے قواعد۔" },
    "p2.li_c1": { en: "A <strong>Research Workbook</strong> showing idea development, research and exploration for all four pieces, plus art appreciation and criticism in context in relation to art making / critical studies.", ne: "<strong>अनुसन्धान कार्यपुस्तिका</strong> चारै कृतिका लागि विचार विकास, अनुसन्धान र अन्वेषण देखाउँछ, साथै कला निर्माण / आलोचनात्मक अध्ययनसँग सम्बन्धित सन्दर्भमा कला प्रशंसा र आलोचना।", ur: "<strong>تحقیقی ورک بک</strong> چاروں کاموں کے لیے خیال کی ترقی، تحقیق اور کھوج دکھاتی ہے، ساتھ فن تخلیق / تنقیدی مطالعے کے سیاق میں فن ستائش و تنقید۔" },
    "p2.li_c2": { en: "<strong>Four pieces</strong> of Artwork / Critical Studies in <strong>one theme</strong> (at least one must be artwork).", ne: "<strong>चार कृति</strong> कलाकृति / आलोचनात्मक अध्ययन <strong>एउटै विषयवस्तु</strong> अन्तर्गत (कम्तीमा एउटा कलाकृति)।", ur: "<strong>چار کام</strong> آرٹ ورک / تنقیدی مطالعہ <strong>ایک ہی موضوع</strong> پر (کم از کم ایک آرٹ ورک)۔" },
    "p2.p_core": { en: "Each student submits <strong>one portfolio</strong> internally assessed by subject teachers. It contains:", ne: "प्रत्येक विद्यार्थीले विषय शिक्षकद्वारा आन्तरिक मूल्याङ्कन गरिएको <strong>एउटा पोर्टफोलियो</strong> पेश गर्छ। यसमा:", ur: "ہر طالب علم مضمون کے استاد کے ذریعے اندرونی جائزے پر مبنی <strong>ایک پورٹ فولیو</strong> جمع کراتا ہے۔ اس میں:" },
    "p2.p_core2": { en: "Develop work in S5 and S6; submit to the school for internal assessment at the end of each year as required. SBA marks go to the HKEAA at the end of S6.", ne: "S5 र S6 मा काम विकास गर्नुहोस्; प्रत्येक वर्षको अन्त्यमा विद्यालयलाई आन्तरिक मूल्याङ्कनका लागि पेश गर्नुहोस्। S6 अन्तमा HKEAA लाई अङ्क जान्छ।", ur: "S5 اور S6 میں کام ترقی دیں؛ ہر سال کے آخر میں اسکول کو اندرونی جائزے کے لیے جمع کرائیں۔ S6 کے آخر میں نمبر HKEAA کو جاتے ہیں۔" },
    "p2.p_mod": { en: "For moderation, the HKEAA may take <strong>not more than 24 pages</strong> from the Research Workbook plus <strong>4 pages of images</strong> (one image page per artwork piece).", ne: "मध्यस्थताका लागि HKEAA ले कार्यपुस्तिकाबाट <strong>२४ पृष्ठभन्दा बढी नलिने</strong> र प्रत्येक कलाकृतिको लागि <strong>४ छवि पृष्ठ</strong> (छवि पृष्ठ प्रति कृति) लिन सक्छ।", ur: "معتدلی کے لیے HKEAA ورک بک سے <strong>۲۴ صفحات سے زیادہ نہیں</strong> نکال سکتا اور ہر آرٹ ورک کے لیے <strong>۴ تصویر والے صفحات</strong>۔" },
    "p2.p_theme": { en: "All four pieces sit under <strong>one theme</strong> (broad theme with sub-themes allowed). Work can be all artwork, or one to three pieces can be critical studies. The handbook lists acceptable genres (drawing, painting, print, photography, sculpture, design, calligraphy, critical studies, etc.) — follow the official handbook for full lists and notes (e.g. 3D and animation submission rules).", ne: "चारै कृति <strong>एउटै विषयवस्तु</strong> अन्तर्गत (फराकिलो विषय, उप-विषयहरू अनुमति)। सबै कलाकृति वा एक देखि तीन आलोचनात्मक अध्ययन हुन सक्छन्। स्वीकार्य विधाहरू पुस्तिकामा सूचीबद्ध छन् — आधिकारिक पुस्तिकामा पूर्ण सूची र नियम (३D, एनिमेसन आदि) हेर्नुहोस्।", ur: "چاروں کام <strong>ایک موضوع</strong> کے تحت (وسیع موضوع، ذیلی موضوعات کی اجازت)۔ سب آرٹ ورک یا ایک سے تین تنقیدی مطالعے۔ قابل قبول اصناف کتابچے میں درج ہیں — مکمل فہرست اور قواعد (۳D، حرکت پذیری وغیرہ) سرکاری کتابچے میں دیکھیں۔" },
    "p2.sp1": { en: "<strong>Transfer (S5→S6 between schools):</strong> S6-only SBA; portfolio = Research Workbook + <strong>two</strong> pieces (at least one artwork); marks adjusted to 50% weighting. S5 SBA at the previous school does not count.", ne: "<strong>स्थानान्तरण (S5→S6 अर्को विद्यालय):</strong> S6 मात्र SBA; पोर्टफोलियो = कार्यपुस्तिका + <strong>दुई</strong> कृति (कम्तीमा एउटा कला); अङ्क ५०% तौलमा समायोजन। अघिल्लो विद्यालयको S5 गणना हुँदैन।", ur: "<strong>منتقلی (S5→S6 دوسرے اسکول):</strong> صرف S6 SBA؛ پورٹ فولیو = ورک بک + <strong>دو</strong> کام (کم از کم ایک آرٹ)؛ نمبر ۵۰٪ وزن میں ترتیب۔ پرانے اسکول کا S5 شمار نہیں۔" },
    "p2.sp2": { en: "<strong>Repeaters:</strong> Generally must be re-assessed in S6 if the school offers VA; previous SBA does not count. Exemption possible only in specific school situations — see handbook.", ne: "<strong>दोहोर्याउने:</strong> सामान्यतया S6 मा पुनः मूल्याङ्कन; पुरानो SBA गणना हुँदैन। छुट विद्यालय अवस्थामा मात्र — पुस्तिका हेर्नुहोस्।", ur: "<strong>دہرانے والے:</strong> عموماً S6 میں دوبارہ جائزہ؛ پرانا SBA شمار نہیں۔ استثناء مخصوص اسکولی حالات میں — کتابچہ دیکھیں۔" },
    "p2.sp3": { en: "<strong>Private candidates:</strong> Submit Research Workbook + two pieces (at least one artwork) to the HKEAA; assessed by appointed assessors; may be interviewed.", ne: "<strong>निजी उम्मेदवार:</strong> कार्यपुस्तिका + दुई कृति (कम्तीमा एउटा कला) HKEAA लाई; नियुक्त मूल्याङ्ककद्वारा मूल्याङ्कन; अन्तर्वार्ता हुन सक्छ।", ur: "<strong>نجی امیدوار:</strong> ورک بک + دو کام (کم از کم ایک آرٹ) HKEAA کو؛ مقرر جائزہ کار؛ انٹرویو ممکن۔" }
  });
})();
