/* Auto-generated: EN/NE/UR strings for part5.html — run node tools/emit-page-bundles.mjs to refresh */
(function () {
  if (!window.SBA_i18n) return;
  window.SBA_i18n.mergeStrings({
    "doc.title.part5": { en: "Part 5 · Administration — VA SBA", ne: "भाग ५ · प्रशासन — VA SBA", ur: "حصہ ۵ · انتظامیہ — VA SBA" },
    "p5.h1": { en: "Part 5 · Administration", ne: "भाग ५ · प्रशासन", ur: "حصہ ۵ · انتظامیہ" },
    "p5.h41": { en: "Participating in SBA (4.1)", ne: "SBA मा सहभागिता (४.१)", ur: "SBA میں شرکت (۴.۱)" },
    "p5.h42": { en: "Late submission and absence (4.2)", ne: "ढिलो पेश र अनुपस्थिति (४.२)", ur: "دیر سے جمع اور غیر حاضری (۴.۲)" },
    "p5.h43": { en: "Students with special educational needs (4.3)", ne: "विशेष शैक्षिक आवश्यकता (४.३)", ur: "خاص تعلیمی ضروریات (۴.۳)" },
    "p5.h44": { en: "Submission of SBA marks (4.4)", ne: "SBA अङ्क पठाउने (४.४)", ur: "SBA نمبر بھیجنا (۴.۴)" },
    "p5.h45": { en: "Declarations &amp; security (4.5–4.6)", ne: "घोषणा र सुरक्षा (४.५–४.६)", ur: "اعلانات اور سیکیورٹی (۴.۵–۴.۶)" },
    "p5.lead": { en: "Chapter 4 — school participation, late work, SEN, mark submission, declarations and security.", ne: "अध्याय ४ — सहभागिता, ढिलो पेश, विशेष शैक्षिक आवश्यकता, अङ्क पठाउने, घोषणा र सुरक्षा।", ur: "باب ۴ — شرکت، دیر سے جمع، خاص تعلیمی ضروریات، نمبر بھیجنا، اعلانات اور سیکیورٹی۔" },
    "p5.p41": { en: "SBA is compulsory for school candidates. Schools that cannot meet handbook requirements may not enter candidates for the subject. The HKEAA may warn, give time to improve, or bar entry until requirements are met.", ne: "विद्यालय उम्मेदवारका लागि SBA अनिवार्य। आवश्यकता पूरा नगर्ने विद्यालयले विषयमा उम्मेदवारी दिन नसक्न सक्छ। HKEAA ले चेतावनी, समय वा प्रवेश रोक्न सक्छ।", ur: "اسکول امیدواروں کے لیے SBA لازمی۔ ضروریات پوری نہ کرنے والے اسکول مضمون میں داخلہ نہ دے سکیں۔ HKEAA انتباہ، مہلت یا داخلہ روک سکتا ہے۔" },
    "p5.p42": { en: "Late work may be penalised per school rules. Legitimate non-completion needs reasons and documentation for special consideration. No legitimate submission can mean zero for that assessment; schools may warn students.", ne: "ढिलो भए विद्यालय नियमअनुसार जरिवाना। वैध कारणमा कागजातसहित विशेष विचार। वैध कारण बिना शून्य सम्भव; चेतावनी पत्र।", ur: "تاخیر پر اسکول کے قواعد کے مطابق جرمانہ۔ جائز وجوہات پر دستاویزات کے ساتھ خصوصی غور۔ بغیر جائز وجہ صفر ممکن؛ انتباہی خط۔" },
    "p5.p43": { en: "Schools may provide equitable arrangements (extra time, aids, etc.). If the school cannot support a case, the principal may write to the HKEAA early in the year for possible partial or full exemption from tasks.", ne: "विद्यालयले उपयुक्त व्यवस्था गर्न सक्छ (अतिरिक्त समय, सहायक उपकरण)। नसकिने अवस्थामा प्रधानले वर्ष सुरुमा HKEAA लाई लेख्नुहोस्।", ur: "اسکول مناسب انتظام دے سکتا ہے (اضافی وقت، معاون آلات)۔ اگر ممکن نہ ہو تو پرنسپل سال کے آغاز میں HKEAA کو لکھیں۔" },
    "p5.p44": { en: "Deadlines are coordinated by the HKEAA; leave time after student completion for internal finalisation and checks. Marks are submitted through the online SBA system; principals endorse before HKEAA submission.", ne: "HKEAA समयसीमा; विद्यार्थी समाप्तिपछि आन्तरिक अन्तिमीकरणका लागि समय छोड्नुहोस्। अनलाइन SBA प्रणाली; प्रधानले अनुमोदन गर्छन्।", ur: "HKEAA کی ڈیڈ لائنیں؛ طالب علم کے ختم ہونے کے بعد اندرونی حتمی کام کے لیے وقت چھوڑیں۔ آن لائن SBA نظام؛ پرنسپل منظوری۔" },
    "p5.p44b": { en: "<strong>One-off submission:</strong> S5 and S6 marks are submitted together in S6; S5 marks are kept at school until then — requirements and conduct of SBA in S5/S6 are unchanged. See HKEAA SBA FAQs for details.", ne: "<strong>एक पटक पठाउने:</strong> S5 र S6 अङ्क S6 मा सँगै; S5 अङ्क विद्यालयमा राखिन्छ — S5/S6 आवश्यकता उही। विवरण HKEAA SBA FAQ मा।", ur: "<strong>ایک بار جمع:</strong> S5 اور S6 نمبر S6 میں ساتھ؛ S5 نمبر اسکول میں رکھے جاتے ہیں — تقاضے وہی۔ تفصیل HKEAA SBA FAQ میں۔" },
    "p5.p45": { en: "Teachers declare conflicts of interest (e.g. assessing relatives). Schools need internal processes for declarations and mitigation. Treat secure materials like internal exams where secrecy matters before assessment.", ne: "शिक्षकले हित द्वन्द्व घोषणा गर्छन् (जस्तै नातेदार मूल्याङ्कन)। आन्तरिक प्रक्रिया र सुरक्षित सामग्री आन्तरिक परीक्षा जस्तै राख्नुहोस्।", ur: "اساتذہ مفادات کے تنازعات کا اعلان کرتے ہیں (جیسے رشتہ داروں کا جائزہ)۔ اندرونی عمل اور محفوظ مواد اندرونی امتحان کی طرح۔" }
  });
})();
