/* Auto-generated: EN/NE/UR strings for part4.html — run node tools/emit-page-bundles.mjs to refresh */
(function () {
  if (!window.SBA_i18n) return;
  window.SBA_i18n.mergeStrings({
    "doc.title.part4": { en: "Part 4 · Conduct of SBA — VA SBA", ne: "भाग ४ · SBA सञ्चालन — VA SBA", ur: "حصہ ۴ · SBA کی ادارت — VA SBA" },
    "p4.h1": { en: "Part 4 · Conduct of SBA", ne: "भाग ४ · SBA सञ्चालन", ur: "حصہ ۴ · SBA کی ادارت" },
    "p4.h_auth": { en: "Authentication (3.3)", ne: "प्रमाणीकरण (३.३)", ur: "تصدیق (۳.۳)" },
    "p4.h_guide": { en: "Teacher guidance (3.2)", ne: "शिक्षक मार्गदर्शन (३.२)", ur: "استاد کی رہنمائی (۳.۲)" },
    "p4.h_info": { en: "Information to students (3.1)", ne: "विद्यार्थीलाई जानकारी (३.१)", ur: "طلباء کو معلومات (۳.۱)" },
    "p4.h_rest": { en: "Queries, records, language (3.5–3.7)", ne: "जिज्ञासा, रेकर्ड, भाषा (३.५–३.७)", ur: "استفسار، ریکارڈ، زبان (۳.۵–۳.۷)" },
    "p4.h_std": { en: "Within-school standardisation (3.4)", ne: "विद्यालय भित्र मानकीकरण (३.४)", ur: "اسکول کے اندر معیار بندی (۳.۴)" },
    "p4.lead": { en: "Chapter 3 — informing students, teacher guidance boundaries, authentication (including AI), standardisation, queries, records and language.", ne: "अध्याय ३ — विद्यार्थीलाई जानकारी, शिक्षक मार्गदर्शन सीमा, प्रमाणीकरण (AI समेत), मानकीकरण, जिज्ञासा, रेकर्ड र भाषा।", ur: "باب ۳ — طلباء کو معلومات، استاد کی رہنمائی کی حدیں، تصدیق (AI سمیت)، معیار بندی، استفسار، ریکارڈ اور زبان۔" },
    "p4.p_auth": { en: "Discuss AI in context: proper use can support learning; using AI for unfair advantage is malpractice and must be acknowledged like other sources. Students keep complete records of their work. Teachers and principals confirm authenticity when submitting marks; no changes to work or records after submission to the HKEAA.", ne: "AI: उचित प्रयोगले सिकाइ सहयोग गर्छ; अनुचित फाइदाका लागि AI दुराचार हो र अरू स्रोत जस्तै उल्लेख गर्नुपर्छ। विद्यार्थीले पूर्ण रेकर्ड राख्छन्। अङ्क पठाउँदा शिक्षक र प्रधानले प्रमाणित गर्छन्; HKEAA पछि काम वा रेकर्ड बदल्न मिल्दैन।", ur: "AI: مناسب استعمال سیکھنے میں مدد؛ غیر منصفانہ فائدے کے لیے AI بدعنوانی ہے اور دوسرے ذرائع کی طرح حوالہ دیں۔ طلباء مکمل ریکارڈ رکھیں۔ نمبر بھیجتے وقت استاد اور پرنسپل تصدیق کرتے ہیں؛ HKEAA کے بعد کام یا ریکارڈ نہیں بدلا جاتا۔" },
    "p4.p_g1": { en: "Guidance should support learning without giving undue help on work that counts toward public results. Work submitted for final assessment cannot be revised for retrospective marking.", ne: "सार्वजनिक परिणाममा गणना हुने काममा अनुचित सहयोग नदिनुहोस्। अन्तिम पेश भएको काम पछि पुनः मूल्याङ्कनका लागि संशोधन गर्न मिल्दैन।", ur: "عوامی نتائج میں شمار ہونے والے کام پر حد سے زیادہ مدد نہ دیں۔ حتمی جمع شدہ کام بعد میں دوبارہ جائزے کے لیے تبدیل نہیں ہو سکتا۔" },
    "p4.p_g2": { en: "<strong>Generally acceptable:</strong> time management, how to acknowledge sources, choosing suitable topics, general questions on early drafts.", ne: "<strong>सामान्यतः स्वीकार्य:</strong> समय व्यवस्थापन, स्रोत उल्लेख, विषय छनोट, मस्यौदामा सामान्य प्रश्न।", ur: "<strong>عموماً قابل قبول:</strong> وقت کا انتظام، ذرائع کا حوالہ، موضوع کا انتخاب، مسودوں پر عام سوالات۔" },
    "p4.p_g3": { en: "<strong>Not acceptable:</strong> rewriting the Research Workbook or redoing idea development for the student.", ne: "<strong>अस्वीकार्य:</strong> कार्यपुस्तिका पुनर्लेखन वा विद्यार्थीका लागि विचार विकास पुनः गर्नु।", ur: "<strong>نامناسب:</strong> ورک بک دوبارہ لکھوانا یا طالب علم کے لیے خیال کی ترقی دوبارہ کرنا۔" },
    "p4.p_info": { en: "At the start of the course, students should know: task requirements and criteria; deadlines; school rules; academic honesty; how to cite sources; record-keeping expectations. Students sign a declaration each year they do SBA. After marking, teachers give feedback; before online mark submission, students should know marks may change after HKEAA moderation.", ne: "कोर्स सुरुमा: कार्य र मापदण्ड, समयसीमा, विद्यालय नियम, शैक्षिक इमान्दारी, उद्धरण, रेकर्ड अपेक्षा। प्रत्येक वर्ष घोषणापत्र हस्ताक्षर। मूल्याङ्कन पछि प्रतिक्रिया; अनलाइन अङ्क पठाउनु अघि मध्यस्थतापछि अङ्क परिवर्तन हुन सक्छ भन्ने जानकारी।", ur: "کورس کے آغاز پر: کام اور معیار، ڈیڈ لائنیں، اسکول کے قواعد، علمی دیانتداری، حوالہ جات، ریکارڈ کی توقعات۔ ہر سال اعلامیہ پر دستخط۔ جائزے کے بعد رائے؛ آن لائن نمبر بھیجنے سے پہلے معتدلی کے بعد نمبروں میں تبدیلی ممکن۔" },
    "p4.p_std": { en: "If more than one teacher teaches the cohort, align criteria and standards (meetings, trial marking, adjustment, use of HKEAA reference and school archives).", ne: "एकभन्दा बढी शिक्षक भए मापदण्ड र मानक मिलाउनुहोस् (बैठक, नमूना मूल्याङ्कन, समायोजन, HKEAA सामग्री)।", ur: "ایک سے زیادہ استاد ہوں تو معیار ملا لیں (میٹنگز، نمونہ جائزہ، ترتیب، HKEAA مواد)۔" },
    "p4.r1": { en: "Schools resolve student queries before marks go to the HKEAA; after results release, recheck applications are possible, but not a full re-assessment of SBA performance.", ne: "अङ्क HKEAA जानुअघि विद्यालयले जिज्ञासा समाधान गर्छ; नतिजा पछि पुनःजाँच आवेदन सम्भव, तर SBA पूर्ण पुनःमूल्याङ्कन होइन।", ur: "نمبر HKEAA جانے سے پہلے اسکول استفسار حل کرے؛ نتائج کے بعد دوبارہ جانچ درخواست ممکن، مگر SBA کا مکمل دوبارہ جائزہ نہیں۔" },
    "p4.r2": { en: "Keep assessment tasks, marks, and irregularity documentation until the end of the examination cycle.", ne: "परीक्षा चक्र अन्त्यसम्म कार्य, अङ्क र अनियमितता कागजात राख्नुहोस्।", ur: "امتحانی چکر کے آخر تک کام، نمبر اور غیر معمولی صورتوں کے کاغذات رکھیں۔" },
    "p4.r3": { en: "Portfolio language should match the school’s medium of instruction policy.", ne: "पोर्टफोलियो भाषा विद्यालयको शिक्षण माध्यम नीतिसँग मेल खानुपर्छ।", ur: "پورٹ فولیو کی زبان اسکول کی تعلیمی زبان کی پالیسی سے مماثل ہو۔" }
  });
})();
