/* Auto-generated: EN/NE/UR strings for part1.html — run node tools/emit-page-bundles.mjs to refresh */
(function () {
  if (!window.SBA_i18n) return;
  window.SBA_i18n.mergeStrings({
    "doc.title.part1": { en: "Part 1 · Introduction — VA SBA", ne: "भाग १ · परिचय — VA SBA", ur: "حصہ ۱ · تعارف — VA SBA" },
    "p1.aim1": { en: "Generate ideas through observation, experience, imagination, technology and other skills.", ne: "अवलोकन, अनुभव, कल्पना, प्रविधि र अन्य सीपबाट विचार उत्पन्न गर्ने।", ur: "مشاہدے، تجربے، تخیل، ٹیکنالوجی اور دیگر مہارتوں سے خیالات پیدا کرنا۔" },
    "p1.aim2": { en: "Develop themes from personal or social concerns using primary and secondary sources.", ne: "प्राथमिक र द्वितीयक स्रोत चयन र व्यवस्थापन गरी व्यक्तिगत वा सामाजिक सरोकारबाट विषयवस्तु विकास गर्ने।", ur: "ذاتی یا سماجی سرودکار سے موضوع ترقی دینا — بنیادی اور ثانوی ذرائع کا انتخاب و انتظام۔" },
    "p1.aim3": { en: "Analyse and interpret artwork / art phenomena in writing, with judgment of form, purpose, meaning and context.", ne: "रूप, उद्देश्य, अर्थ र संदर्भको निर्णयसहित लेखनमा कलाकृति / कला घटना विश्लेषण गर्ने।", ur: "تحریر میں فن پارے / فن واقعات کا تجزیہ — شکل، مقصد، معنی اور سیاق پر فیصلہ۔" },
    "p1.aim4": { en: "Bring together appreciation, criticism and learning from other areas into art-making.", ne: "कला प्रशंसा, आलोचना र अन्य क्षेत्रको सिकाइलाई कला निर्माणमा जोड्ने।", ur: "فن ستائش، تنقید اور دوسرے شعبوں کی سیکھ کو فن تخلیق سے جوڑنا۔" },
    "p1.aim5": { en: "Choose and use visual language, media, materials and techniques for creative expression.", ne: "रचनात्मक अभिव्यक्ति वा समस्याको समाधानका लागि दृश्य भाषा, माध्यम, सामग्री र सीप छान्ने।", ur: "بصری زبان، ذریعہ، مواد اور مہارتیں تخلیقی اظہار یا مسئلے کے حل کے لیے۔" },
    "p1.aim6": { en: "Reflect on and evaluate their own and others’ work and improve over time.", ne: "आफ्नो र अरूको काममा निरन्तर पुनर्विचार, मूल्याङ्कन र सुधार गर्ने।", ur: "اپنے اور دوسروں کے کام پر مسلسل غور، جائزہ اور بہتری۔" },
    "p1.h1": { en: "Part 1 · Introduction", ne: "भाग १ · परिचय", ur: "حصہ ۱ · تعارف" },
    "p1.h_aims": { en: "Aims of SBA (what teachers assess)", ne: "SBA का उद्देश्यहरू (शिक्षक के माप्छन्)", ur: "SBA کے مقاصد (استاد کیا ناپتے ہیں)" },
    "p1.h_fw": { en: "Assessment framework", ne: "मूल्याङ्कन ढाँचा", ur: "جائزے کا ڈھانچہ" },
    "p1.h_s56": { en: "S5 / S6 task split (summary)", ne: "S5 / S6 कार्य विभाजन (सारांश)", ur: "S5 / S6 کام کی تقسیم (خلاصہ)" },
    "p1.lead": { en: "Preface, handbook changes, and Chapter 1 — how Visual Arts SBA fits the public assessment and what it aims to measure.", ne: "प्रस्तावना, पुस्तिका परिवर्तन, र अध्याय १ — VA SBA सार्वजनिक मूल्याङ्कनमा कसरी बस्छ र के माप्न खोजिन्छ।", ur: "دیباچہ، کتابچے کی تبدیلیاں، اور باب ۱ — VA SBA عوامی جائزے میں کیسے فٹ ہوتا ہے اور کیا ناپا جاتا ہے۔" },
    "p1.li_fw1": { en: "<strong>Public examination (50%)</strong> — Paper 1 (theme / visual presentation) or Paper 2 (Design); each paper has Part A (10%) and Part B (40%); 4 hours total.", ne: "<strong>सार्वजनिक परीक्षा (५०%)</strong> — कागजात १ (विषयवस्तु / दृश्य प्रस्तुति) वा कागजात २ (डिजाइन); प्रत्येकमा भाग A (१०%) र भाग B (४०%); जम्मा ४ घण्टा।", ur: "<strong>عوامی امتحان (۵۰٪)</strong> — پیپر ۱ (موضوع / بصری پیشکش) یا پیپر ۲ (ڈیزائن); ہر پیپر میں حصہ A (۱۰٪) اور حصہ B (۴۰٪); کل ۴ گھنٹے۔" },
    "p1.li_fw2": { en: "<strong>School-based assessment (50%)</strong> — One portfolio: Research Workbook (20%) and four pieces of Artwork / Critical Studies for your theme(s) (30%), with at least one piece as artwork. Work spans S5 and S6.", ne: "<strong>विद्यालय आधारित मूल्याङ्कन (५०%)</strong> — एउटा पोर्टफोलियो: अनुसन्धान कार्यपुस्तिका (२०%) र तपाईंको विषय(हरू)का लागि चार कलाकृति / आलोचनात्मक अध्ययन (३०%), कम्तीमा एउटा कलाकृति। काम S5 र S6 मा।", ur: "<strong>اسکول پر مبنی جائزہ (۵۰٪)</strong> — ایک پورٹ فولیو: تحقیقی ورک بک (۲۰٪) اور آپ کے موضوع (موضوعات) پر چار آرٹ ورک / تنقیدی مطالعہ (۳۰٪)، کم از کم ایک آرٹ ورک۔ کام S5 اور S6 میں۔" },
    "p1.note": { en: "<strong>Note.</strong> Portfolios show sustained work and progress over time — selection, reflection, justification and improvement should be visible.", ne: "<strong>टिप्पणी।</strong> पोर्टफोलियोले लामो समयको काम र प्रगति देखाउँछ — चयन, पुनर्विचार, औचित्य र सुधार देखिनुपर्छ।", ur: "<strong>نوٹ۔</strong> پورٹ فولیو طویل مدتی کام اور ترقی دکھاتا ہے — انتخاب، غور، جواز اور بہتری نظر آنی چاہیے۔" },
    "p1.p_aims": { en: "SBA should reflect students’ ability to:", ne: "SBA ले विद्यार्थीको यी क्षमता देखाउनुपर्छ:", ur: "SBA کو طلباء کی یہ صلاحیتیں دکھانی چاہئیں:" },
    "p1.p_fw": { en: "Public assessment follows the Visual Arts Curriculum and Assessment Guide (S4–6). It has two components:", ne: "सार्वजनिक मूल्याङ्कन दृश्य कला पाठ्यक्रम र मूल्याङ्कन मार्गदर्शन (S4–6) अनुसार छ। यसमा दुई भाग छन्:", ur: "عوامی جائزہ بصریات نصاب و جائزہ رہنمائی (S4–6) پر مبنی ہے۔ اس میں دو حصے ہیں:" },
    "p1.s56_1": { en: "<strong>S5:</strong> Two pieces of Artwork / Critical Studies (15% of subject).", ne: "<strong>S5:</strong> दुई कलाकृति / आलोचनात्मक अध्ययन (विषयको १५%)।", ur: "<strong>S5:</strong> دو آرٹ ورک / تنقیدی مطالعہ (مضمون کا ۱۵٪)۔" },
    "p1.s56_2": { en: "<strong>S6:</strong> Two pieces of Artwork / Critical Studies plus the Research Workbook (15% + 20%).", ne: "<strong>S6:</strong> दुई कलाकृति / आलोचनात्मक अध्ययन प्लस अनुसन्धान कार्यपुस्तिका (१५% + २०%)।", ur: "<strong>S6:</strong> دو آرٹ ورک / تنقیدی مطالعہ مزید تحقیقی ورک بک (۱۵٪ + ۲۰٪)۔" }
  });
})();
