/* Auto-generated: EN/NE/UR strings for index.html (data-page part0) — run node tools/emit-page-bundles.mjs to refresh */
(function () {
  if (!window.SBA_i18n) return;
  window.SBA_i18n.mergeStrings({
    "doc.title.part0": { en: "Start here · How to do well — VA SBA", ne: "सुरु गर्नुहोस् · कसरी राम्रो गर्ने — VA SBA", ur: "شروع کریں · اچھی کارکردگی — VA SBA" },
    "p0.f1": { en: "<strong>Skills.</strong> Show control of the media or writing you chose (including critical studies if you do them).", ne: "<strong>सीप।</strong> तपाईंले छानेको माध्यम वा लेखनमा नियन्त्रण देखाउनुहोस् (आलोचनात्मक अध्ययन भए पनि)।", ur: "<strong>مہارت۔</strong> منتخب ذریعہ یا تحریر پر قابو دکھائیں (تنقیدی مطالعہ سمیت)۔" },
    "p0.f2": { en: "<strong>Visual language.</strong> Use elements and composition on purpose, tied to your theme — not random decoration.", ne: "<strong>दृश्य भाषा।</strong> तत्व र कम्पोजिसन जानाजानी विषयवस्तुसँग जोडेर प्रयोग गर्नुहोस् — सजावट मात्र होइन।", ur: "<strong>بصری زبان۔</strong> عناصر اور ترکیب جان بوجھ کر موضوع سے جوڑیں — بے مقصد سجاوٹ نہیں۔" },
    "p0.f3": { en: "<strong>Context.</strong> Link the work to personal, cultural or aesthetic meaning — not only “it looks nice.”", ne: "<strong>संदर्भ।</strong> व्यक्तिगत, सांस्कृतिक वा सौन्दर्य अर्थसँग जोड्नुहोस् — मात्र “राम्रो देखिन्छ” मात्र होइन।", ur: "<strong>سیاق و سباق۔</strong> ذاتی، ثقافتی یا جمالیاتی معنی سے جوڑیں — صرف “اچھا لگتا ہے” نہیں۔" },
    "p0.f4": { en: "<strong>Ideas.</strong> Aim for clear, personal responses; avoid copying one artist or one style without adding your own angle.", ne: "<strong>विचारहरू।</strong> स्पष्ट, व्यक्तिगत प्रतिक्रिया; एक कलाकार वा शैली नकल गर्दा आफ्नो कोण थप्नुहोस्।", ur: "<strong>خیالات۔</strong> واضح ذاتی ردعمل؛ کسی فنکار یا انداز کی نقل بغیر اپنا زاویہ۔" },
    "p0.f5": { en: "<strong>Communication.</strong> Someone should understand what your theme is without you standing next to the work.", ne: "<strong>सञ्चार।</strong> तपाईं काम नजिक नभई पनि विषयवस्तु बुझिनुपर्छ।", ur: "<strong>مواصلات۔</strong> آپ کے بغیر بھی موضوع سمجھ آنا چاہیے۔" },
    "p0.f6": { en: "<strong>Progression.</strong> All four pieces should feel like one journey — weaker early attempts are fine if later pieces show growth.", ne: "<strong>क्रमिक प्रगति।</strong> चारै कृति एउटा यात्रा जस्तो लाग्नुपर्छ — सुरु कमजोर भए पनि पछिल्ला कृतिमा वृद्धि देखिनुपर्छ।", ur: "<strong>سلسلہ وار ترقی۔</strong> چاروں کام ایک سفر جیسے لگیں — ابتدائی کمزوری بعد میں بہتری سے ٹھیک ہے۔" },
    "p0.h1": { en: "Start here · How to do well", ne: "सुरु गर्नुहोस् · कसरी राम्रो गर्ने", ur: "شروع کریں · اچھی کارکردگی کیسے" },
    "p0.h_four": { en: "Do well on the four pieces", ne: "चार कृतिमा राम्रो गर्नुहोस्", ur: "چار کاموں میں اچھا کرنا" },
    "p0.h_graded": { en: "What you are graded on", ne: "तपाईंलाई के मूल्याङ्कन गरिन्छ", ur: "آپ کا جائزہ کس بنیاد پر ہوتا ہے" },
    "p0.h_mark": { en: "About your final mark", ne: "अन्तिम अङ्कको बारेमा", ur: "آخری نمبر کے بارے میں" },
    "p0.h_rw": { en: "Do well on the Research Workbook", ne: "अनुसन्धान कार्यपुस्तिकामा राम्रो गर्नुहोस्", ur: "تحقیقی ورک بک میں اچھا کرنا" },
    "p0.h_school": { en: "How you work with school", ne: "विद्यालयसँग कसरी काम गर्ने", ur: "اسکول کے ساتھ کام" },
    "p0.lead": { en: "The short version: what actually moves your SBA mark, distilled from the official handbook and the other topics in the menu. Read this first; when you need detail on rules and rubrics, use <strong>Introduction &amp; framework</strong>, <strong>Requirements &amp; portfolio</strong>, and <strong>Assessment criteria</strong>.", ne: "छोटो संस्करण: तपाईंको SBA अङ्क केले हलचल गर्छ भन्ने, आधिकारिक पुस्तिका र मेनुका अन्य विषयबाट निष्कर्ष। पहिले यो पढ्नुहोस्; नियम र रुब्रिक विस्तारमा <strong>परिचय र ढाँचा</strong>, <strong>आवश्यकता र पोर्टफोलियो</strong>, र <strong>मूल्याङ्कन मापदण्ड</strong> प्रयोग गर्नुहोस्।", ur: "مختصر خلاصہ: آپ کے SBA نمبر کو کیا حرکت دیتا ہے — سرکاری کتابچے اور مینو کے دیگر حصوں سے۔ پہلے یہ پڑھیں؛ قواعد اور رُبّرک تفصیل کے لیے <strong>تعارف اور ڈھانچہ</strong>، <strong>ضروریات اور پورٹ فولیو</strong>، اور <strong>جائزہ معیار</strong> کھولیں۔" },
    "p0.li_rw1": { en: "<strong>Develop one theme properly.</strong> Use varied sources (not one website), organise them, and push ideas forward — not just collect pictures.", ne: "<strong>एउटा विषयवस्तु राम्रोसँग विकास गर्नुहोस्।</strong> विविध स्रोत (एउटा वेबसाइट मात्र होइन) प्रयोग गर्नुहोस्, व्यवस्थित गर्नुहोस्, र विचार अगाडि बढाउनुहोस् — तस्बिर मात्र जम्मा नगर्नुहोस्।", ur: "<strong>ایک موضوع اچھی طرح ترقی دیں۔</strong> متنوع ذرائع (صرف ایک ویب سائٹ نہیں) استعمال کریں، ترتیب دیں، اور خیالات آگے بڑھائیں — صرف تصاویر جمع نہ کریں۔" },
    "p0.li_rw2": { en: "<strong>Show art knowledge that feeds your work.</strong> Notice context and formal qualities of artworks; say what <em>you</em> think, with reasons; connect that thinking to your own making or critical studies.", ne: "<strong>आफ्नो कामलाई पोषण गर्ने कला ज्ञान देखाउनुहोस्।</strong> कलाकृतिको संदर्भ र औपचारिक गुणहरू ध्यान दिनुहोस्; <em>तपाईं</em> के सोच्नुहुन्छ कारणसहित भन्नुहोस्; त्यो सोच आफ्नो निर्माण वा आलोचनात्मक अध्ययनसँग जोड्नुहोस्।", ur: "<strong>فن سے وابستہ علم دکھائیں جو آپ کے کام کو پوشیدہ رکھے۔</strong> فن پارے کا سیاق اور باقاعدہ خصوصیات دیکھیں؛ <em>آپ</em> کیا سوچتے ہیں وجوہات کے ساتھ کہیں؛ اسے اپنے تخلیق یا تنقیدی مطالعے سے جوڑیں۔" },
    "p0.li_rw3": { en: "<strong>Experiment.</strong> Try media, skills and ways of expressing the theme — the workbook should show trials, not only tidy finals.", ne: "<strong>प्रयोग गर्नुहोस्।</strong> माध्यम, सीप र विषयवस्तु व्यक्त गर्ने तरिका प्रयास गर्नुहोस् — कार्यपुस्तिकामा परीक्षणहरू देखिनुपर्छ, मात्र सफा अन्तिम मात्र होइन।", ur: "<strong>تجربہ کریں۔</strong> ذریعہ، مہارتیں اور موضوع کے اظہار کے طریقے آزمائیں — ورک بک میں تجربات نظر آنے چاہئیں، نہ کہ صرف صاف حتمی شکل۔" },
    "p0.li_rw4": { en: "<strong>Reflect.</strong> Look back at what worked, what failed, and what you changed. Progress should read clearly across the portfolio.", ne: "<strong>पुनर्विचार गर्नुहोस्।</strong> के काम गर्‍यो, के असफल भयो, के परिवर्तन गर्नुभयो हेर्नुहोस्। प्रगति पोर्टफोलियोभरि स्पष्ट पढिनुपर्छ।", ur: "<strong>غور و فکر کریں۔</strong> کیا کام ہوا، کیا ناکام، کیا بدلا — پورٹ فولیو میں ترقی واضح پڑھنی چاہیے۔" },
    "p0.note": { en: "<strong class=\"note__label\">Want more?</strong> Open <strong>Introduction &amp; framework</strong> and <strong>Requirements &amp; portfolio</strong> for exact requirements, <strong>Assessment criteria</strong> for the full rubrics, and <strong>Conduct of SBA</strong> for rules on teacher guidance and keeping records. <strong>Administration</strong>, <strong>Moderation</strong>, and <strong>Malpractice &amp; appendices</strong> are mainly for teachers and school processes.", ne: "<strong class=\"note__label\">थप चाहिन्छ?</strong> सही आवश्यकताका लागि <strong>परिचय र ढाँचा</strong> र <strong>आवश्यकता र पोर्टफोलियो</strong>, पूर्ण रुब्रिकका लागि <strong>मूल्याङ्कन मापदण्ड</strong>, शिक्षक मार्गदर्शन र रेकर्ड राख्ने नियमका लागि <strong>SBA सञ्चालन</strong> खोल्नुहोस्। <strong>प्रशासन</strong>, <strong>मध्यस्थता</strong>, र <strong>दुराचार र परिशिष्ट</strong> मुख्यतः शिक्षक र विद्यालय प्रक्रियाका लागि हुन्।", ur: "<strong class=\"note__label\">مزید؟</strong> درست ضروریات کے لیے <strong>تعارف اور ڈھانچہ</strong> اور <strong>ضروریات اور پورٹ فولیو</strong>، مکمل رُبّرک کے لیے <strong>جائزہ معیار</strong>، استاد کی رہنمائی اور ریکارڈ کے قواعد کے لیے <strong>SBA کی ادارت</strong> کھولیں۔ <strong>انتظامیہ</strong>، <strong>معتدلی</strong>، اور <strong>بدعنوانی اور ضمائم</strong> زیادہ تر اساتذہ اور اسکول کے عمل کے لیے ہیں۔" },
    "p0.p_graded": { en: "Visual Arts SBA is <strong>half your subject mark</strong>. You submit <strong>one portfolio</strong>: a <strong>Research Workbook</strong> plus <strong>four pieces</strong> under <strong>one theme</strong> (at least one piece must be artwork). Work is spread over <strong>S5 and S6</strong>. Teachers mark you against fixed criteria — not on “talent” alone, but on how clearly your folder shows ideas, research, skills, context and improvement.", ne: "दृश्य कला SBA तपाईंको विषय अङ्कको <strong>आधा</strong> हो। तपाईंले <strong>एउटा पोर्टफोलियो</strong> पेश गर्नुहुन्छ: <strong>अनुसन्धान कार्यपुस्तिका</strong> र <strong>एउटा विषयवस्तु अन्तर्गत चार कृति</strong> (कम्तीमा एउटा कलाकृति)। काम <strong>S5 र S6</strong> मा फैलिन्छ। शिक्षकले निश्चित मापदण्डअनुसार मूल्याङ्कन गर्छन् — केवल “प्रतिभा” मात्र होइन, तर तपाईंको फोल्डरले विचार, अनुसन्धान, सीप, संदर्भ र सुधार कति स्पष्ट देखाउँछ।", ur: "بصریات SBA آپ کے مضمون کے نصف نمبروں پر مشتمل ہے۔ آپ <strong>ایک پورٹ فولیو</strong> جمع کراتے ہیں: <strong>تحقیقی ورک بک</strong> اور <strong>ایک موضوع پر چار کام</strong> (کم از کم ایک آرٹ ورک)۔ کام <strong>S5 اور S6</strong> پر پھیلتا ہے۔ اساتذہ مقررہ معیار سے نمبر دیتے ہیں — صرف “ذہانت” نہیں، بلکہ یہ کہ آپ کا فولڈر خیالات، تحقیق، مہارت، سیاق اور بہتری کتنی واضح دکھاتا ہے۔" },
    "p0.p_mark": { en: "The HKEAA may <strong>adjust</strong> school marks so standards match across Hong Kong, but your <strong>rank among classmates</strong> in your school usually stays the same. Focus on doing your portfolio well against the criteria; don’t waste energy comparing schools.", ne: "HKEAA ले मानक मिलाउन विद्यालय अङ्क <strong>समायोजन</strong> गर्न सक्छ, तर तपाईंको विद्यालयभित्र साथीभाइमा <strong>दर्जा</strong> सामान्यतया उही रहन्छ। मापदण्डअनुसार पोर्टफोलियोमा ध्यान दिनुहोस्; विद्यालय तुलना गर्न ऊर्जा नखर्च्नुहोस्।", ur: "HKEAA معیار یکساں کرنے کے لیے اسکول نمبروں میں <strong>ترمیم</strong> کر سکتا ہے، مگر آپ کے اسکول میں ہم جماعتوں میں <strong>درجہ</strong> عام طور پر وہی رہتا ہے۔ معیار پر توجہ دیں؛ اسکولوں کی بے جا تقابلی نہ کریں۔" },
    "p0.s1": { en: "<strong>Use time across two years.</strong> Rushed work shows in both the workbook and the four pieces.", ne: "<strong>दुई वर्षको समय प्रयोग गर्नुहोस्।</strong> हतारको काम कार्यपुस्तिका र चारै कृतिमा देखिन्छ।", ur: "<strong>دو سال کا وقت استعمال کریں۔</strong> جلد بازی ورک بک اور چاروں کاموں میں نظر آتی ہے۔" },
    "p0.s2": { en: "<strong>Bring drafts early.</strong> Teachers can give general help at the start; they should not rewrite your work — plan so you are not asking for that.", ne: "<strong>मस्यौदा चाँडो ल्याउनुहोस्।</strong> सुरुमा शिक्षकले सामान्य मार्गदर्शन दिन सक्छन्; तपाईंको काम पुनर्लेखन गर्नु हुँदैन — त्यसो नमाग्न योजना बनाउनुहोस्।", ur: "<strong>مسودے جلدی لائیں۔</strong> شروع میں استاد عام رہنمائی دے سکتے ہیں؛ آپ کا کام دوبارہ لکھوانا درست نہیں — منصوبہ بنائیں۔" },
    "p0.s3": { en: "<strong>Follow your school’s schedule and language policy.</strong> Meet internal deadlines so marks can be submitted on time.", ne: "<strong>विद्यालयको तालिका र भाषा नीति पालन गर्नुहोस्।</strong> आन्तरिक समयसीमा भेट्नुहोस् ताकि अङ्क समयमा पठाइयोस्।", ur: "<strong>اسکول کے شیڈول اور زبان کی پالیسی پر عمل کریں۔</strong> اندرونی ڈیڈ لائنیں پوری کریں تاکہ نمبر وقت پر جائیں۔" }
  });
})();
