/* Auto-generated: EN/NE/UR strings for part3.html — run node tools/emit-page-bundles.mjs to refresh */
(function () {
  if (!window.SBA_i18n) return;
  window.SBA_i18n.mergeStrings({
    "doc.title.part3": { en: "Part 3 · Assessment criteria — VA SBA", ne: "भाग ३ · मूल्याङ्कन मापदण्ड — VA SBA", ur: "حصہ ۳ · جائزہ معیار — VA SBA" },
    "p3.a1": { en: "<strong>Media, skills and techniques</strong> — Command of materials and techniques (or writing for critical studies).", ne: "<strong>माध्यम, सीप र तवर</strong> — सामग्री र तवर (वा आलोचनात्मक लेखन) मा नियन्त्रण।", ur: "<strong>ذریعہ، مہارتیں اور طریقہ</strong> — مواد اور طریقہ (یا تنقیدی تحریر) پر قابو۔" },
    "p3.a2": { en: "<strong>Visual presentation / analysis</strong> — Use of visual elements and principles of organisation in relation to the theme.", ne: "<strong>दृश्य प्रस्तुति / विश्लेषण</strong> — विषयवस्तुसँग दृश्य तत्व र संगठनका सिद्धान्त।", ur: "<strong>بصری پیشکش / تجزیہ</strong> — موضوع سے بصری عناصر اور تنظیم کے اصول۔" },
    "p3.a3": { en: "<strong>Relationship with context</strong> — Personal, aesthetic or cultural context linked to the theme.", ne: "<strong>संदर्भसँग सम्बन्ध</strong> — व्यक्तिगत, सौन्दर्य वा सांस्कृतिक संदर्भ।", ur: "<strong>سیاق سے تعلق</strong> — ذاتی، جمالیاتی یا ثقافتی سیاق۔" },
    "p3.a4": { en: "<strong>Creativity and imagination / critical thinking</strong> — Originality and quality of ideas or argued personal views.", ne: "<strong>सिर्जनशीलता / आलोचनात्मक सोच</strong> — मौलिकता वा तर्कसहित व्यक्तिगत दृष्टिकोण।", ur: "<strong>تخلیقیت / تنقیدی سوچ</strong> — اصلیت یا دلیل کے ساتھ ذاتی نقطہ نظر۔" },
    "p3.a5": { en: "<strong>Overall presentation and communication of theme</strong> — Clarity and coherence of the message or theme.", ne: "<strong>समग्र प्रस्तुति र विषयवस्तु सञ्चार</strong> — सन्देश वा विषयवस्तुको स्पष्टता र एकरूपता।", ur: "<strong>مجموعی پیشکش اور موضوع کی ترسیل</strong> — پیغام یا موضوع کی وضاحت اور ہم آہنگی۔" },
    "p3.a6": { en: "<strong>Progression of all four pieces</strong> — Evidence of development across the set.", ne: "<strong>चारै कृतिको प्रगति</strong> — समूहभरि विकासको प्रमाण।", ur: "<strong>چاروں کاموں کی ترقی</strong> — مجموعے میں ترقی کا ثبوت۔" },
    "p3.h1": { en: "Part 3 · Assessment criteria", ne: "भाग ३ · मूल्याङ्कन मापदण्ड", ur: "حصہ ۳ · جائزہ معیار" },
    "p3.h_art": { en: "Artwork / Critical Studies (four pieces, one theme) — criteria (summary)", ne: "कलाकृति / आलोचनात्मक अध्ययन (चार कृति, एउटै विषय) — सारांश", ur: "آرٹ ورک / تنقیدی مطالعہ (چار کام، ایک موضوع) — خلاصہ" },
    "p3.h_rw": { en: "Research Workbook — criteria (summary)", ne: "अनुसन्धान कार्यपुस्तिका — मापदण्ड (सारांश)", ur: "تحقیقی ورک بک — معیار (خلاصہ)" },
    "p3.lead": { en: "Chapter 2.4 — marks reflect rank order and differences between students. Assessment uses 0–5 rubrics. Zero if work does not meet minimum standard. Full descriptors are in the official handbook (pp. 8–11) and sample sheets in Appendices E–F.", ne: "अध्याय २.४ — अङ्कले दर्जा र विद्यार्थीबीच भिन्नता देखाउँछ। ०–५ रुब्रिक। न्यूनतम मानक नपुगे शून्य। पूर्ण वर्णन आधिकारिक पुस्तिका (पृ. ८–११) र परिशिष्ट E–F मा।", ur: "باب ۲.۴ — نمبر درجے اور فرق دکھاتے ہیں۔ ۰–۵ رُبّرک۔ کم از کم معیار نہ پورا ہو تو صفر۔ مکمل بیان سرکاری کتابچے (ص ۸–۱۱) اور ضمیمہ E–F میں۔" },
    "p3.note": { en: "<strong>Teachers.</strong> Use the official rubric tables for marking; these pages are a reading guide only.", ne: "<strong>शिक्षकहरू।</strong> मूल्याङ्कनका लागि आधिकारिक रुब्रिक तालिका प्रयोग गर्नुहोस्; यी पृष्ठ पढ्ने मार्गदर्शन मात्र हुन्।", ur: "<strong>اساتذہ۔</strong> نمبر دینے کے لیے سرکاری رُبّرک جدول استعمال کریں؛ یہ صفحات صرف مطالعے کی رہنمائی ہیں۔" },
    "p3.rw1": { en: "<strong>Exploration and development of theme or ideas</strong> — Range and depth of sources; selecting, organising and integrating materials; moving toward more original / personal ideas.", ne: "<strong>विषयवस्तु वा विचारको अन्वेषण र विकास</strong> — स्रोतको दायरा र गहिराइ; सामग्री चयन, व्यवस्थापन र एकीकरण; मौलिक / व्यक्तिगत विचारतर्फ।", ur: "<strong>موضوع یا خیال کی کھوج اور ترقی</strong> — ذرائع کی وسعت اور گہرائی؛ انتخاب، انتظام اور یکجائی؛ مزید اصلی / ذاتی خیالات۔" },
    "p3.rw2": { en: "<strong>Interpretation of artworks and link to art making / critical studies</strong> — Understanding context and formal qualities; personal views with evidence; applying that knowledge to own work.", ne: "<strong>कलाकृतिको व्याख्या र कला निर्माण / आलोचनात्मक अध्ययनसँग जोड</strong> — संदर्भ र औपचारिक गुण; प्रमाणसहित व्यक्तिगत दृष्टिकोण; आफ्नो काममा प्रयोग।", ur: "<strong>فن پارے کی تشریح اور فن تخلیق / تنقیدی مطالعے سے جوڑ</strong> — سیاق اور باقاعدہ خصوصیات؛ ثبوت کے ساتھ ذاتی نقطہ نظر؛ اپنے کام پر اطلاق۔" },
    "p3.rw3": { en: "<strong>Experimentation of media and skills; exploration of expression</strong> — Breadth and depth of media/skill trials and expressive exploration.", ne: "<strong>माध्यम र सीपको प्रयोग; अभिव्यक्तिको अन्वेषण</strong> — माध्यम/सीप परीक्षण र अभिव्यक्तिको गहिराइ।", ur: "<strong>ذریعے اور مہارتوں کا استعمال؛ اظہار کی کھوج</strong> — ذریعہ/مہارت کے تجربات اور اظہار کی گہرائی۔" },
    "p3.rw4": { en: "<strong>Reflection and progression in learning</strong> — How consistently the student reflects and shows improvement across the portfolio.", ne: "<strong>सिकाइमा पुनर्विचार र प्रगति</strong> — पोर्टफोलियोभरि पुनर्विचार र सुधार कति नियमित।", ur: "<strong>سیکھنے میں غور اور ترقی</strong> — پورٹ فولیو میں غور اور بہتری کتنی باقاعدہ۔" }
  });
})();
